/*
 * App URI: 9-Dialogs/Host
 * Source Location: 9-Dialogs/Host.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("9-Dialogs/Host", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/*
			 * "Button" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2( /* cpr.events.CMouseEvent */ e) {
				var grid = app.lookup("grd1");
				var data = grid.getSelectedRow().getRowData();
			
				app.openDialog("9-Dialogs/Dialog", {
					width: 400,
					height: 300
				}, function(dialog) {
					dialog.ready(function() {
						dialog.setAppProperty("initData", data);
					});
					dialog.style.animateFrom({
						"opacity": "0",
						"transform": "translateY(-100px) rotateX(90deg)"
					});
				}).then(function(returnValue) {
					console.log("값이 수정되었습니다.");
					grid.getSelectedRow().setRowData(returnValue);
					grid.redraw();
				});
			}
			
			/*
			 * 그리드에서 cell-click 이벤트 발생 시 호출.
			 * Grid의 Cell 클릭시 발생하는 이벤트.
			 */
			function onGrd1CellClick( /* cpr.events.CGridEvent */ e) {
				if (e.cellIndex == 1) {
					onButtonClick2(null);
				}
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "name"},
					{"name": "gender"},
					{
						"name": "age",
						"dataType": "number"
					}
				],
				"rows": [
					{"name": "스티브 잡스", "gender": "male", "age": "42"},
					{"name": "에이미 파울러", "gender": "female", "age": "32"},
					{"name": "홍길동", "gender": "male", "age": "41"},
					{"name": "마리아 스크워도프스카 퀴리", "gender": "female", "age": "32"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.readOnly = true;
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columnMovable": false,
				"columnResizable": false,
				"autoFit": "0",
				"columns": [
					{"width": "258px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [{
						"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 2},
						"configurator": function(cell){
							cell.targetColumnName = "name";
							cell.filterable = false;
							cell.sortable = false;
							cell.text = "명단";
						}
					}]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "name";
								cell.control = (function(){
									var output_1 = new cpr.controls.Output();
									output_1.bind("value").toExpression([
										"name",
										"+ \" (\" ",
										"+ switch(gender){",
										"\tcase \"female\" : \"여\"",
										"\tcase \"male\" : \"남\"",
										"}",
										"+ \", \"",
										"+ age",
										"+ \"세)\""
									].join("\n"));
									return output_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.style.css({
									"color" : "#333333"
								});
								cell.control = (function(){
									var button_1 = new cpr.controls.Button();
									button_1.value = "편집";
									button_1.style.css({
										"color" : "#333333"
									});
									if(typeof onButtonClick2 == "function") {
										button_1.addEventListener("click", onButtonClick2);
									}
									return button_1;
								})();
							}
						}
					]
				}
			});
			if(typeof onGrd1CellClick == "function") {
				grid_1.addEventListener("cell-click", onGrd1CellClick);
			}
			container.addChild(grid_1, {
				"top": "20px",
				"right": "20px",
				"bottom": "20px",
				"left": "20px"
			});
		}
	});
	app.title = "Host";
	cpr.core.Platform.INSTANCE.register(app);
})();
