/*
 * App URI: 2-Publish/4-MultiLayerCSS
 * Source Location: 2-Publish/4-MultiLayerCSS.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("2-Publish/4-MultiLayerCSS", {
		onPrepare: function(loader){
			loader.addCSS("2-Publish/mario.css");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Daisy";
			button_1.style.setClasses(["daisy-button"]);
			container.addChild(button_1, {
				"top": "242px",
				"left": "20px",
				"width": "474px",
				"height": "81px"
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "Mario";
			button_2.style.setClasses(["mario-button"]);
			container.addChild(button_2, {
				"top": "111px",
				"left": "20px",
				"width": "474px",
				"height": "121px"
			});
			
			var button_3 = new cpr.controls.Button();
			button_3.value = "Daisy";
			button_3.style.setClasses(["daisy-button"]);
			container.addChild(button_3, {
				"top": "20px",
				"left": "262px",
				"width": "232px",
				"height": "81px"
			});
			
			var button_4 = new cpr.controls.Button();
			button_4.value = "Mario";
			button_4.style.setClasses(["mario-button"]);
			container.addChild(button_4, {
				"top": "20px",
				"left": "20px",
				"width": "232px",
				"height": "81px"
			});
		}
	});
	app.title = "4-MultiLayerCSS";
	cpr.core.Platform.INSTANCE.register(app);
})();
