/*
 * App URI: template/layout/grid/md_gridfreeform
 * Source Location: template/layout/grid/md_gridfreeform.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("template/layout/grid/md_gridfreeform", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			// 공통 Util
			var comUtil = createComUtil(app);
			
			/*
			 * Body에서 init 이벤트 발생 시 호출. 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit(/* cpr.events.CEvent */e) {
				// 페이지 인덱서 초기화
				comUtil.setPagingInfo("resPage", "pageIndexer");
			}
			
			/*
			 * "초기화" 버튼에서 click 이벤트 발생 시 호출. 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(/* cpr.events.CMouseEvent */e) {
				/**
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				// 변경 데이터 체크
				if (comUtil.isUpdated("resList") == true) {
					var isOk = confirm("변경된 정보가 있습니다. 저장하시겠습니까?");
					if (isOk == true) {
						// 목록저장
						doSave();
						return;
					}
				}
			
				/** 화면초기화 * */
				// 검색조건 초기화
				var reqKey = app.lookup("reqKey");
				reqKey.reset();
			
				var grpSearch = app.lookup("grp_search");
				grpSearch.redraw();
			
				// 목록 초기화
				var resList = app.lookup("resList");
				resList.clear();
				app.lookup("grdMain").redraw();
			
				// 입력부 초기화
				var frm = app.lookup("grp_frm");
				frm.getBindContext().rowIndex = -1;
				frm.redraw();
			
				// 페이지 인덱서 설정초기화
				var resPage = app.lookup("resPage");
				resPage.reset();
			
				// 페이지 인덱서 초기화
				comUtil.setPagingInfo("resPage", "pageIndexer");
			}
			
			/*
			 * 그룹에서 keydown 이벤트 발생 시 호출. 사용자가 키를 누를 때 발생하는 이벤트.
			 */
			function onGrp_searchKeydown(/* cpr.events.CKeyboardEvent */e) {
				/**
				 * @type cpr.controls.Container
				 */
				var grp_search = e.control;
			
				// 검색부에서 enter key가 입력되면 자동 조회
				if (e.keyCode == cpr.events.KeyCode.ENTER) {
					// 화면 조회
					doSearch();
				}
			}
			
			/*
			 * "검색" 버튼에서 click 이벤트 발생 시 호출. 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(/* cpr.events.CMouseEvent */e) {
				/**
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				// 화면 조회
				doSearch();
			}
			
			/*
			 * 메인 검색 Function
			 */
			function doSearch() {
				// validation 검색 조건 입력 검증.
				var isValid = comUtil.validate("grp_search");
				if (isValid == false) {
					return;
				}
			
				// 조회 Submission Send
				comUtil.send("subMainList");
			}
			
			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출. 통신이 성공하면 발생합니다.
			 */
			function onSubMainListSubmitSuccess(/* cpr.events.CSubmissionEvent */e) {
				/**
				 * @type cpr.protocols.Submission
				 */
				var subMainList = e.control;
			
				// 서버로부터 전달된 메시지가 있을 경우 메시지를 출력
				var message = subMainList.getMetadata("msg");
				if (message) {
					comUtil.alert(message);
				}
			
				// 메인그리드를 redraw
				var grdMain = app.lookup("grdMain");
				grdMain.redraw();
			
				if (grdMain.rowCount > 0) {
					// 첫번째 row 선택
					grdMain.selectRows([ 0 ]);
				} else {
					// 조회된 결과가 없을 경우 조건을 초기화
					var frm = app.lookup("grp_frm");
					frm.getBindContext().rowIndex = -1;
					frm.redraw();
				}
			
				// 페이지 인덱서 반영
				comUtil.setPagingInfo("resPage", "pageIndexer");
			}
			
			/*
			 * 사용자 정의 컨트롤에서 before-pagechange 이벤트 발생 시 호출.
			 */
			function onPageIndexerBeforePagechange(/* cpr.events.CSelectionEvent */e) {
				/**
				 * @type udc.pageindex
				 */
				var pageIndexer = e.control;
			
				// 변경 데이터 체크
				if (comUtil.isUpdated("resList") == true) {
					var isOk = confirm("변경된 정보가 있습니다. 저장하시겠습니까?");
					if (isOk == true) {
						// 목록을 저장하고 다음 이벤트 중지
						doSave();
						e.preventDefault();
						return;
					}
				}
				// 조회조건 validation
				var isValid = comUtil.validate("grp_search");
				// 조회조건이 invalid 할 때 다음 이벤트 중지
				if (isValid == false) {
					// 다음 이벤트 중지
					e.preventDefault();
					return;
				}
			}
			
			/*
			 * 페이지 이동. 사용자 정의 컨트롤에서 pagechange 이벤트 발생 시 호출.
			 */
			function onPageIndexerPagechange(/* cpr.events.CSelectionEvent */e) {
				/**
				 * @type udc.pageindex
				 */
				var pageIndexer = e.control;
			
				// 변경된 페이지 인덱스를 DataMap에 반영
				var resPage = app.lookup("resPage");
				resPage.setValue("pageIdx", e.newSelection);
			
				// 조회 서브미션 send
				doSearch();
			}
			
			/*
			 * 그리드에서 before-selection-change 이벤트 발생 시 호출. detail의 cell 클릭하여 설정된 selectionunit에 해당되는 단위가 선택되기 전에 발생하는 이벤트입니다.
			 */
			function onGrdMainBeforeSelectionChange(/* cpr.events.CSelectionEvent */e) {
				/**
				 * @type cpr.controls.Grid
				 */
				var grdMain = e.control;
				// 새로운 row가 선택되기 이전의 row.
				var oldSel = e.oldSelection;
			
				// 이전 선택된 Row가 없으면 스킵
				if (oldSel == null || oldSel.length == 0) {
					return;
				}
				// 이전 선택된 Row가 삭제된 Row이면 스킵
				var grdRow = grdMain.getRow(oldSel[0]);
				if (grdRow.getStateString().indexOf("D") != -1) {
					return;
				}
			
				// 입력부의 Validation
			//	var isValid = comUtil.validate("grp_frm");
			//	if (isValid == false) {
			//		// 변경이 유효하지 않을 경우 진행 중지
			//		e.preventDefault();
			//	}
			}
			
			/*
			 * "저장" 버튼에서 click 이벤트 발생 시 호출. 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick3(/* cpr.events.CMouseEvent */e) {
				/**
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				// 목록 저장
				doSave();
			}
			
			/*
			 * 메인 저장 Function
			 */
			function doSave() {
				// 변경여부 확인
				if (comUtil.isUpdated("resList") == false) {
					comUtil.alert("변경된 정보가 없습니다.");
					return;
				}
			
				// Validation 입력부 체크
				var isValid = comUtil.validate("grp_frm");
				if (isValid == false) {
					// 검증 실패 시 처리 중단
					return;
				}
			
				// 저장 Submission send
				comUtil.send("subSave");
			}
			
			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출. 통신이 성공하면 발생합니다.
			 */
			function onSubSaveSubmitSuccess(/* cpr.events.CSubmissionEvent */e) {
				/**
				 * @type cpr.protocols.Submission
				 */
				var subSave = e.control;
			
				// 서버로 부터 전달된 메시지가 있을 경우 메시지 출력
				var message = subSave.getMetadata("msg");
				if (message) {
					comUtil.alert(message);
				}
			
				// 화면 재조회
				doSearch();
			}
			
			/*
			 * 사용자 정의 컨트롤에서 insert 이벤트 발생 시 호출.
			 */
			function onButton_gridInsert(/* cpr.events.CUIEvent */e) {
				/**
				 * @type udc.button_grid
				 */
				var button_grid = e.control;
			
				// 그리드 row insert
				comUtil.insertGridRow("grdMain");
			
				// 입력 가능한 첫 번째 셀에 포커스
				app.focus("ipdFrmColumn1");
			}
			
			/*
			 * 사용자 정의 컨트롤에서 delete 이벤트 발생 시 호출.
			 */
			function onButton_gridDelete(/* cpr.events.CUIEvent */e) {
				/**
				 * @type udc.button_grid
				 */
				var button_grid = e.control;
			
				// 그리드 선택된 Row 삭제
				comUtil.deleteGridRow("grdMain");
			
				// Row가 삭제되면 입력부를 새로 그림
				app.lookup("grp_frm").redraw();
			}
			
			/*
			 * 사용자 정의 컨트롤에서 reset 이벤트 발생 시 호출.
			 */
			function onButton_gridReset(/* cpr.events.CUIEvent */e) {
				/**
				 * @type udc.button_grid
				 */
				var button_grid = e.control;
			
				// 그리드 선택된 Row undo
				var rowIndex = comUtil.revertGridRow("grdMain");
				if (rowIndex != -1) {
					// 데이터가 복구되면 입력부를 새로 그림
					app.lookup("grp_frm").redraw();
				}
			}
			
			/*
			 * "Export" 버튼에서 click 이벤트 발생 시 호출. 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick4(/* cpr.events.CMouseEvent */e) {
				/**
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				// Excel Export
				comUtil.exportExcel("grdMain", "마스터-디테일 (그리드-프리폼)");
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			var dataSet_1 = new cpr.data.DataSet("resList");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"}
				],
				"rows": []
			});
			app.register(dataSet_1);
			var dataMap_1 = new cpr.data.DataMap("reqKey");
			dataMap_1.parseData({
				"alterColumnLayout": "client",
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"}
				]
			});
			app.register(dataMap_1);
			
			var dataMap_2 = new cpr.data.DataMap("resPage");
			dataMap_2.parseData({
				"alterColumnLayout": "client",
				"columns": [
					{
						"name": "totCnt",
						"dataType": "number",
						"defaultValue": "0"
					},
					{
						"name": "pageSize",
						"dataType": "number",
						"defaultValue": "0"
					},
					{
						"name": "rowSize",
						"dataType": "number",
						"defaultValue": "0"
					},
					{
						"name": "pageIdx",
						"dataType": "number",
						"defaultValue": "1"
					}
				]
			});
			app.register(dataMap_2);
			var submission_1 = new cpr.protocols.Submission("subMainList");
			submission_1.action = "../template/md_gridfreeform/getMainList.do";
			submission_1.addRequestData(dataMap_1);
			submission_1.addRequestData(dataMap_2);
			submission_1.addResponseData(dataSet_1, false);
			submission_1.addResponseData(dataMap_2, false);
			if(typeof onSubMainListSubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSubMainListSubmitSuccess);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("subSave");
			submission_2.action = "../template/md_gridfreeform/save.do";
			submission_2.addRequestData(dataSet_1);
			if(typeof onSubSaveSubmitSuccess == "function") {
				submission_2.addEventListener("submit-success", onSubSaveSubmitSuccess);
			}
			app.register(submission_2);
			
			app.supportMedia("all and (min-width: 1800px)", "new-screen");
			app.supportMedia("all and (max-width: 1799px)", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.setColumns(["1fr", "450px"]);
			formLayout_1.setRows(["100px", "40px", "1fr", "11px", "38px"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container("grp_search");
				group_2.style.setClasses(["grp-search"]);
				// Layout
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.setColumns(["70px", "130px", "70px", "130px", "70px", "130px", "1fr", "90px"]);
				formLayout_2.setRows(["1fr", "1fr", "1fr"]);
				group_2.setLayout(formLayout_2);
				(function(container){
					var inputBox_1 = new cpr.controls.InputBox("ipdColumn1");
					inputBox_1.userAttr({
						"required": "Y",
						"name": "컬럼1"
					});
					inputBox_1.style.setClasses(["required"]);
					inputBox_1.bind("value").toDataMap(app.lookup("reqKey"), "column1");
					container.addChild(inputBox_1, {
						"colIndex": 1,
						"rowIndex": 0
					});
					var inputBox_2 = new cpr.controls.InputBox("ipdColumn2");
					inputBox_2.bind("value").toDataMap(app.lookup("reqKey"), "column2");
					container.addChild(inputBox_2, {
						"colIndex": 3,
						"rowIndex": 0
					});
					var inputBox_3 = new cpr.controls.InputBox("ipdColumn3");
					inputBox_3.bind("value").toDataMap(app.lookup("reqKey"), "column3");
					container.addChild(inputBox_3, {
						"colIndex": 5,
						"rowIndex": 0
					});
					var inputBox_4 = new cpr.controls.InputBox("ipdColumn4");
					inputBox_4.bind("value").toDataMap(app.lookup("reqKey"), "column4");
					container.addChild(inputBox_4, {
						"colIndex": 1,
						"rowIndex": 1
					});
					var inputBox_5 = new cpr.controls.InputBox("ipdColumn5");
					inputBox_5.bind("value").toDataMap(app.lookup("reqKey"), "column5");
					container.addChild(inputBox_5, {
						"colIndex": 3,
						"rowIndex": 1
					});
					var inputBox_6 = new cpr.controls.InputBox("ipdColumn6");
					inputBox_6.bind("value").toDataMap(app.lookup("reqKey"), "column6");
					container.addChild(inputBox_6, {
						"colIndex": 5,
						"rowIndex": 1
					});
					var inputBox_7 = new cpr.controls.InputBox("ipdColumn7");
					inputBox_7.bind("value").toDataMap(app.lookup("reqKey"), "column7");
					container.addChild(inputBox_7, {
						"colIndex": 1,
						"rowIndex": 2
					});
					var inputBox_8 = new cpr.controls.InputBox("ipdColumn8");
					inputBox_8.bind("value").toDataMap(app.lookup("reqKey"), "column8");
					container.addChild(inputBox_8, {
						"colIndex": 3,
						"rowIndex": 2
					});
					var inputBox_9 = new cpr.controls.InputBox("ipdColumn9");
					inputBox_9.bind("value").toDataMap(app.lookup("reqKey"), "column9");
					container.addChild(inputBox_9, {
						"colIndex": 5,
						"rowIndex": 2
					});
					var button_1 = new cpr.controls.Button("btn_reset");
					button_1.value = "초기화";
					if(typeof onButtonClick2 == "function") {
						button_1.addEventListener("click", onButtonClick2);
					}
					container.addChild(button_1, {
						"colIndex": 7,
						"rowIndex": 1
					});
					var button_2 = new cpr.controls.Button("btn_search");
					button_2.value = "검색";
					if(typeof onButtonClick == "function") {
						button_2.addEventListener("click", onButtonClick);
					}
					container.addChild(button_2, {
						"colIndex": 7,
						"rowIndex": 2
					});
					var output_1 = new cpr.controls.Output();
					output_1.value = "column1";
					container.addChild(output_1, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "column4";
					container.addChild(output_2, {
						"colIndex": 0,
						"rowIndex": 1
					});
					var output_3 = new cpr.controls.Output();
					output_3.value = "column7";
					container.addChild(output_3, {
						"colIndex": 0,
						"rowIndex": 2
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "column2";
					container.addChild(output_4, {
						"colIndex": 2,
						"rowIndex": 0
					});
					var output_5 = new cpr.controls.Output();
					output_5.value = "column5";
					container.addChild(output_5, {
						"colIndex": 2,
						"rowIndex": 1
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "column8";
					container.addChild(output_6, {
						"colIndex": 2,
						"rowIndex": 2
					});
					var output_7 = new cpr.controls.Output();
					output_7.value = "column3";
					container.addChild(output_7, {
						"colIndex": 4,
						"rowIndex": 0
					});
					var output_8 = new cpr.controls.Output();
					output_8.value = "column6";
					container.addChild(output_8, {
						"colIndex": 4,
						"rowIndex": 1
					});
					var output_9 = new cpr.controls.Output();
					output_9.value = "column9";
					container.addChild(output_9, {
						"colIndex": 4,
						"rowIndex": 2
					});
				})(group_2);
				if(typeof onGrp_searchKeydown == "function") {
					group_2.addEventListener("keydown", onGrp_searchKeydown);
				}
				container.addChild(group_2, {
					"colIndex": 0,
					"rowIndex": 0,
					"colSpan": 2,
					"rowSpan": 1
				});
				var userDefinedControl_1 = new udc.pageindex("pageIndexer");
				if(typeof onPageIndexerBeforePagechange == "function") {
					userDefinedControl_1.addEventListener("before-pagechange", onPageIndexerBeforePagechange);
				}
				if(typeof onPageIndexerPagechange == "function") {
					userDefinedControl_1.addEventListener("pagechange", onPageIndexerPagechange);
				}
				container.addChild(userDefinedControl_1, {
					"colIndex": 0,
					"rowIndex": 1,
					"colSpan": 2,
					"rowSpan": 1,
					"height": 30
				});
				var grid_1 = linker.grid_1 = new cpr.controls.Grid("grdMain");
				grid_1.readOnly = true;
				grid_1.init({
					"dataSet": app.lookup("resList"),
					"columnMovable": true,
					"columnResizable": true,
					"noDataMessage": "조회된 데이터가 없습니다.",
					"columns": [
						{"width": "60px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.text = "column1";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.text = "column2";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.text = "column3";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
									cell.text = "column4";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.text = "column5";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.text = "column6";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.text = "column7";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 8},
								"configurator": function(cell){
									cell.text = "column8";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 9},
								"configurator": function(cell){
									cell.text = "column9";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 10},
								"configurator": function(cell){
									cell.text = "column10";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.columnName = "column1";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.columnName = "column2";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.columnName = "column3";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
									cell.columnName = "column4";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.columnName = "column5";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.columnName = "column6";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.columnName = "column7";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 8},
								"configurator": function(cell){
									cell.columnName = "column8";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 9},
								"configurator": function(cell){
									cell.columnName = "column9";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 10},
								"configurator": function(cell){
									cell.columnName = "column10";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.columnType = "rowindex";
									cell.style.css({
										"text-align" : "center"
									});
								}
							}
						]
					}
				});
				if(typeof onGrdMainBeforeSelectionChange == "function") {
					grid_1.addEventListener("before-selection-change", onGrdMainBeforeSelectionChange);
				}
				container.addChild(grid_1, {
					"colIndex": 0,
					"rowIndex": 2,
					"colSpan": 1,
					"rowSpan": 1
				});
				var group_3 = linker.group_3 = new cpr.controls.Container("grp_frm");
				group_3.style.setClasses(["grp-freeform"]);
				group_3.bind("enabled").toExpression("(getStateString() *= \"D\") == false");
				// Layout
				var formLayout_3 = new cpr.controls.layouts.FormLayout();
				formLayout_3.horizontalSeparatorClass = "frm-hseparator";
				formLayout_3.horizontalSeparatorWidth = 1;
				formLayout_3.verticalSeparatorClass = "frm-vseparator";
				formLayout_3.verticalSeparatorWidth = 1;
				formLayout_3.setColumns(["70px", "1fr", "70px", "1fr"]);
				formLayout_3.setRows(["25px", "25px", "25px", "25px", "25px", "1fr"]);
				group_3.setLayout(formLayout_3);
				(function(container){
					var output_10 = new cpr.controls.Output();
					output_10.value = "column1";
					output_10.style.setClasses(["ctl-header"]);
					output_10.style.css({
						"background-color" : "#e3f4fa"
					});
					container.addChild(output_10, {
						"colIndex": 0,
						"rowIndex": 0,
						"verticalAlign": "center"
					});
					var inputBox_10 = new cpr.controls.InputBox("ipdFrmColumn1");
					inputBox_10.autoSelect = true;
					inputBox_10.userAttr({
						"required": "Y",
						"name": "컬럼1"
					});
					inputBox_10.style.setClasses(["required"]);
					inputBox_10.bind("value").toDataColumn("column1");
					inputBox_10.bind("enabled").toExpression("getStateString() *= \"I\"");
					container.addChild(inputBox_10, {
						"colIndex": 1,
						"rowIndex": 0,
						"verticalAlign": "center"
					});
					var output_11 = new cpr.controls.Output();
					output_11.value = "column2";
					output_11.style.setClasses(["ctl-header"]);
					container.addChild(output_11, {
						"colIndex": 2,
						"rowIndex": 0,
						"verticalAlign": "center"
					});
					var inputBox_11 = new cpr.controls.InputBox("ipdFrmColumn2");
					inputBox_11.autoSelect = true;
					inputBox_11.userAttr({
						"required": "Y",
						"name": "컬럼2"
					});
					inputBox_11.style.setClasses(["required"]);
					inputBox_11.bind("value").toDataColumn("column2");
					container.addChild(inputBox_11, {
						"colIndex": 3,
						"rowIndex": 0,
						"verticalAlign": "center"
					});
					var output_12 = new cpr.controls.Output();
					output_12.value = "column3";
					output_12.style.setClasses(["ctl-header"]);
					container.addChild(output_12, {
						"colIndex": 0,
						"rowIndex": 1,
						"verticalAlign": "center"
					});
					var inputBox_12 = new cpr.controls.InputBox("ipb12");
					inputBox_12.autoSelect = true;
					inputBox_12.bind("value").toDataColumn("column3");
					container.addChild(inputBox_12, {
						"colIndex": 1,
						"rowIndex": 1,
						"verticalAlign": "center"
					});
					var output_13 = new cpr.controls.Output();
					output_13.value = "column4";
					output_13.style.setClasses(["ctl-header"]);
					container.addChild(output_13, {
						"colIndex": 2,
						"rowIndex": 1,
						"verticalAlign": "center"
					});
					var inputBox_13 = new cpr.controls.InputBox("ipb19");
					inputBox_13.autoSelect = true;
					inputBox_13.bind("value").toDataColumn("column4");
					container.addChild(inputBox_13, {
						"colIndex": 3,
						"rowIndex": 1,
						"verticalAlign": "center"
					});
					var output_14 = new cpr.controls.Output();
					output_14.value = "column5";
					output_14.style.setClasses(["ctl-header"]);
					container.addChild(output_14, {
						"colIndex": 0,
						"rowIndex": 2,
						"verticalAlign": "center"
					});
					var inputBox_14 = new cpr.controls.InputBox("ipb13");
					inputBox_14.autoSelect = true;
					inputBox_14.bind("value").toDataColumn("column5");
					container.addChild(inputBox_14, {
						"colIndex": 1,
						"rowIndex": 2,
						"verticalAlign": "center"
					});
					var output_15 = new cpr.controls.Output();
					output_15.value = "column6";
					output_15.style.setClasses(["ctl-header"]);
					container.addChild(output_15, {
						"colIndex": 2,
						"rowIndex": 2,
						"verticalAlign": "center"
					});
					var inputBox_15 = new cpr.controls.InputBox("ipb20");
					inputBox_15.autoSelect = true;
					inputBox_15.bind("value").toDataColumn("column6");
					container.addChild(inputBox_15, {
						"colIndex": 3,
						"rowIndex": 2,
						"verticalAlign": "center"
					});
					var output_16 = new cpr.controls.Output();
					output_16.value = "column7";
					output_16.style.setClasses(["ctl-header"]);
					container.addChild(output_16, {
						"colIndex": 0,
						"rowIndex": 3,
						"verticalAlign": "center"
					});
					var inputBox_16 = new cpr.controls.InputBox("ipb14");
					inputBox_16.autoSelect = true;
					inputBox_16.bind("value").toDataColumn("column7");
					container.addChild(inputBox_16, {
						"colIndex": 1,
						"rowIndex": 3,
						"verticalAlign": "center"
					});
					var output_17 = new cpr.controls.Output();
					output_17.value = "column8";
					output_17.style.setClasses(["ctl-header"]);
					container.addChild(output_17, {
						"colIndex": 2,
						"rowIndex": 3,
						"verticalAlign": "center"
					});
					var inputBox_17 = new cpr.controls.InputBox("ipb21");
					inputBox_17.autoSelect = true;
					inputBox_17.bind("value").toDataColumn("column8");
					container.addChild(inputBox_17, {
						"colIndex": 3,
						"rowIndex": 3,
						"verticalAlign": "center"
					});
					var output_18 = new cpr.controls.Output();
					output_18.value = "column9";
					output_18.style.setClasses(["ctl-header"]);
					container.addChild(output_18, {
						"colIndex": 0,
						"rowIndex": 4,
						"verticalAlign": "center"
					});
					var inputBox_18 = new cpr.controls.InputBox("ipb15");
					inputBox_18.autoSelect = true;
					inputBox_18.bind("value").toDataColumn("column9");
					container.addChild(inputBox_18, {
						"colIndex": 1,
						"rowIndex": 4,
						"verticalAlign": "center"
					});
					var output_19 = new cpr.controls.Output();
					output_19.value = "column10";
					output_19.style.setClasses(["ctl-header"]);
					container.addChild(output_19, {
						"colIndex": 2,
						"rowIndex": 4,
						"verticalAlign": "center"
					});
					var inputBox_19 = new cpr.controls.InputBox("ipb22");
					inputBox_19.autoSelect = true;
					inputBox_19.bind("value").toDataColumn("column10");
					container.addChild(inputBox_19, {
						"colIndex": 3,
						"rowIndex": 4,
						"verticalAlign": "center"
					});
					var group_4 = new cpr.controls.Container();
					// Layout
					var xYLayout_2 = new cpr.controls.layouts.XYLayout();
					group_4.setLayout(xYLayout_2);
					(function(container){
					})(group_4);
					container.addChild(group_4, {
						"colIndex": 0,
						"rowIndex": 5,
						"colSpan": 4,
						"rowSpan": 1,
						"verticalAlign": "fill"
					});
				})(group_3);
				container.addChild(group_3, {
					"colIndex": 1,
					"rowIndex": 2,
					"colSpan": 1,
					"rowSpan": 2
				});
				var userDefinedControl_2 = new udc.button_grid("grd_btn");
				if(typeof onButton_gridInsert == "function") {
					userDefinedControl_2.addEventListener("insert", onButton_gridInsert);
				}
				if(typeof onButton_gridDelete == "function") {
					userDefinedControl_2.addEventListener("delete", onButton_gridDelete);
				}
				if(typeof onButton_gridReset == "function") {
					userDefinedControl_2.addEventListener("reset", onButton_gridReset);
				}
				container.addChild(userDefinedControl_2, {
					"colIndex": 0,
					"rowIndex": 3,
					"horizontalAlign": "right",
					"verticalAlign": "fill",
					"width": 70,
					"height": 20
				});
				var group_5 = new cpr.controls.Container();
				group_5.style.setClasses(["grp-buttons"]);
				// Layout
				var formLayout_4 = new cpr.controls.layouts.FormLayout();
				formLayout_4.setColumns(["1fr", "90px", "90px"]);
				formLayout_4.setRows(["1fr"]);
				group_5.setLayout(formLayout_4);
				(function(container){
					var button_3 = new cpr.controls.Button();
					button_3.value = "저장";
					button_3.style.setClasses(["cl-button-box"]);
					if(typeof onButtonClick3 == "function") {
						button_3.addEventListener("click", onButtonClick3);
					}
					container.addChild(button_3, {
						"colIndex": 2,
						"rowIndex": 0,
						"colSpan": 1,
						"rowSpan": 1,
						"horizontalAlign": "fill",
						"verticalAlign": "fill"
					});
					var button_4 = new cpr.controls.Button();
					button_4.value = "Export";
					if(typeof onButtonClick4 == "function") {
						button_4.addEventListener("click", onButtonClick4);
					}
					container.addChild(button_4, {
						"colIndex": 1,
						"rowIndex": 0
					});
				})(group_5);
				container.addChild(group_5, {
					"colIndex": 0,
					"rowIndex": 4,
					"colSpan": 2,
					"rowSpan": 1
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "44px",
				"right": "10px",
				"bottom": "10px",
				"left": "10px"
			});
			
			var userDefinedControl_3 = new udc.pagetitle();
			userDefinedControl_3.bind("title").toAppProperty("title");
			container.addChild(userDefinedControl_3, {
				"top": "10px",
				"right": "10px",
				"left": "10px",
				"height": "24px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
			// Linking
			linker.group_3.setBindContext(new cpr.bind.GridSelectionContext(linker.grid_1));
		}
	});
	app.title = "md_gridfreeform";
	cpr.core.Platform.INSTANCE.register(app);
})();
