/*
 * App URI: login/login
 * Source Location: login/login.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("login/login", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			// 공통 Util 생성
			var comUtil = createComUtil(app);
			
			
			/*
			 * "확인" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				
				var subLogin = app.lookup("sub_login");
				subLogin.send();
			}
			
			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSub_loginSubmitSuccess(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var sub_login = e.control;
				
				var appId = sub_login.getMetadata("uri");
				var msg = sub_login.getMetadata("message");
				if(msg != null) {
					alert(msg);
				}
			
				if (appId != null) {
					// 화면이동
					cpr.core.App.load(appId, function(newapp) {
						app.close();
						newapp.createNewInstance().run();
					});
					return;
				}
			}
			
			/*
			 * 서브미션에서 submit-error 이벤트 발생 시 호출.
			 * 통신 중 문제가 생기면 발생합니다.
			 */
			function onSub_loginSubmitError(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var sub_login = e.control;
				
				var msg = sub_login.getMetadata("message");
				if(msg != null) {
					alert(msg);
				}
			}
			
			/*
			 * 인풋 박스에서 keydown 이벤트 발생 시 호출.
			 * 사용자가 키를 누를 때 발생하는 이벤트.
			 */
			function onIpb2Keydown(/* cpr.events.CKeyboardEvent */ e){
				/** 
				 * @type cpr.controls.InputBox
				 */
				var ipb2 = e.control;
				
				if(e.keyCode == cpr.events.KeyCode.ENTER) {
					app.lookup("btnLogin").click();
				}
			};
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("dm_login");
			dataMap_1.parseData({
				"columns" : [
					{"name": "user_id"},
					{"name": "user_pass"}
				]
			});
			app.register(dataMap_1);
			var submission_1 = new cpr.protocols.Submission("sub_login");
			submission_1.action = "login.do";
			submission_1.addRequestData(dataMap_1);
			if(typeof onSub_loginSubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSub_loginSubmitSuccess);
			}
			if(typeof onSub_loginSubmitError == "function") {
				submission_1.addEventListener("submit-error", onSub_loginSubmitError);
			}
			app.register(submission_1);
			
			app.supportMedia("all", "main");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["cl-main"]);
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"background-color" : "#efefef"
			});
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.topMargin = "50";
			formLayout_1.rightMargin = "50";
			formLayout_1.bottomMargin = "50";
			formLayout_1.leftMargin = "50";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["1fr", "30px", "30px", "30px", "30px"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var image_1 = new cpr.controls.Image();
				image_1.src = "images/exb6_logo.png";
				image_1.alt = "eXbuilder6 로고";
				container.addChild(image_1, {
					"colIndex": 0,
					"rowIndex": 0,
					"colSpan": 1,
					"rowSpan": 1,
					"horizontalAlign": "center",
					"verticalAlign": "center",
					"width": 176,
					"height": 36
				});
				var inputBox_1 = new cpr.controls.InputBox("ipb1");
				inputBox_1.tooltip = "ID를 입력하세요";
				inputBox_1.placeholder = "ID";
				inputBox_1.bind("value").toDataMap(app.lookup("dm_login"), "user_id");
				container.addChild(inputBox_1, {
					"colIndex": 0,
					"rowIndex": 1,
					"verticalAlign": "center"
				});
				var inputBox_2 = new cpr.controls.InputBox("ipb2");
				inputBox_2.tooltip = "비밀번호를 입력하세요";
				inputBox_2.secret = true;
				inputBox_2.placeholder = "PW";
				inputBox_2.bind("value").toDataMap(app.lookup("dm_login"), "user_pass");
				if(typeof onIpb2Keydown == "function") {
					inputBox_2.addEventListener("keydown", onIpb2Keydown);
				}
				container.addChild(inputBox_2, {
					"colIndex": 0,
					"rowIndex": 2,
					"colSpan": 1,
					"rowSpan": 1,
					"verticalAlign": "center"
				});
				var checkBox_1 = new cpr.controls.CheckBox("cbx1");
				checkBox_1.value = "";
				checkBox_1.text = "ID 저장";
				checkBox_1.style.css({
					"text-align" : "left"
				});
				container.addChild(checkBox_1, {
					"colIndex": 0,
					"rowIndex": 3,
					"colSpan": 1,
					"rowSpan": 1
				});
				var button_1 = new cpr.controls.Button("btnLogin");
				button_1.value = "LOGIN";
				if(typeof onButtonClick == "function") {
					button_1.addEventListener("click", onButtonClick);
				}
				container.addChild(button_1, {
					"colIndex": 0,
					"rowIndex": 4,
					"verticalAlign": "center"
				});
			})(group_1);
			container.addChild(group_1, {
				"width": "350px",
				"height": "350px",
				"left": "calc(50% - 175px)",
				"top": "calc(50% - 175px)"
			});
		}
	});
	app.title = "로그인";
	cpr.core.Platform.INSTANCE.register(app);
})();
