/*
 * App URI: 1-Layout/2-Menu
 * Source Location: 1-Layout/2-Menu.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("1-Layout/2-Menu", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"}
				],
				"rows": [
					{"column1": "column11", "column2": "column21", "column3": "column31", "column4": "column41", "column5": "column51", "column6": "column61", "column7": "column71", "column8": "column81", "column9": "column91"},
					{"column1": "column12", "column2": "column22", "column3": "column32", "column4": "column42", "column5": "column52", "column6": "column62", "column7": "column72", "column8": "column82", "column9": "column92"},
					{"column1": "column13", "column2": "column23", "column3": "column33", "column4": "column43", "column5": "column53", "column6": "column63", "column7": "column73", "column8": "column83", "column9": "column93"},
					{"column1": "column14", "column2": "column24", "column3": "column34", "column4": "column44", "column5": "column54", "column6": "column64", "column7": "column74", "column8": "column84", "column9": "column94"},
					{"column1": "column15", "column2": "column25", "column3": "column35", "column4": "column45", "column5": "column55", "column6": "column65", "column7": "column75", "column8": "column85", "column9": "column95"},
					{"column1": "column16", "column2": "column26", "column3": "column36", "column4": "column46", "column5": "column56", "column6": "column66", "column7": "column76", "column8": "column86", "column9": "column96"},
					{"column1": "column17", "column2": "column27", "column3": "column37", "column4": "column47", "column5": "column57", "column6": "column67", "column7": "column77", "column8": "column87", "column9": "column97"},
					{"column1": "column18", "column2": "column28", "column3": "column38", "column4": "column48", "column5": "column58", "column6": "column68", "column7": "column78", "column8": "column88", "column9": "column98"},
					{"column1": "column19", "column2": "column29", "column3": "column39", "column4": "column49", "column5": "column59", "column6": "column69", "column7": "column79", "column8": "column89", "column9": "column99"},
					{"column1": "column110", "column2": "column210", "column3": "column310", "column4": "column410", "column5": "column510", "column6": "column610", "column7": "column710", "column8": "column810", "column9": "column910"},
					{"column1": "column111", "column2": "column211", "column3": "column311", "column4": "column411", "column5": "column511", "column6": "column611", "column7": "column711", "column8": "column811", "column9": "column911"},
					{"column1": "column112", "column2": "column212", "column3": "column312", "column4": "column412", "column5": "column512", "column6": "column612", "column7": "column712", "column8": "column812", "column9": "column912"},
					{"column1": "column113", "column2": "column213", "column3": "column313", "column4": "column413", "column5": "column513", "column6": "column613", "column7": "column713", "column8": "column813", "column9": "column913"},
					{"column1": "column114", "column2": "column214", "column3": "column314", "column4": "column414", "column5": "column514", "column6": "column614", "column7": "column714", "column8": "column814", "column9": "column914"},
					{"column1": "column115", "column2": "column215", "column3": "column315", "column4": "column415", "column5": "column515", "column6": "column615", "column7": "column715", "column8": "column815", "column9": "column915"},
					{"column1": "column116", "column2": "column216", "column3": "column316", "column4": "column416", "column5": "column516", "column6": "column616", "column7": "column716", "column8": "column816", "column9": "column916"},
					{"column1": "column117", "column2": "column217", "column3": "column317", "column4": "column417", "column5": "column517", "column6": "column617", "column7": "column717", "column8": "column817", "column9": "column917"},
					{"column1": "column118", "column2": "column218", "column3": "column318", "column4": "column418", "column5": "column518", "column6": "column618", "column7": "column718", "column8": "column818", "column9": "column918"},
					{"column1": "column119", "column2": "column219", "column3": "column319", "column4": "column419", "column5": "column519", "column6": "column619", "column7": "column719", "column8": "column819", "column9": "column919"},
					{"column1": "column120", "column2": "column220", "column3": "column320", "column4": "column420", "column5": "column520", "column6": "column620", "column7": "column720", "column8": "column820", "column9": "column920"},
					{"column1": "column121", "column2": "column221", "column3": "column321", "column4": "column421", "column5": "column521", "column6": "column621", "column7": "column721", "column8": "column821", "column9": "column921"},
					{"column1": "column122", "column2": "column222", "column3": "column322", "column4": "column422", "column5": "column522", "column6": "column622", "column7": "column722", "column8": "column822", "column9": "column922"},
					{"column1": "column123", "column2": "column223", "column3": "column323", "column4": "column423", "column5": "column523", "column6": "column623", "column7": "column723", "column8": "column823", "column9": "column923"},
					{"column1": "column124", "column2": "column224", "column3": "column324", "column4": "column424", "column5": "column524", "column6": "column624", "column7": "column724", "column8": "column824", "column9": "column924"},
					{"column1": "column125", "column2": "column225", "column3": "column325", "column4": "column425", "column5": "column525", "column6": "column625", "column7": "column725", "column8": "column825", "column9": "column925"},
					{"column1": "column126", "column2": "column226", "column3": "column326", "column4": "column426", "column5": "column526", "column6": "column626", "column7": "column726", "column8": "column826", "column9": "column926"},
					{"column1": "column127", "column2": "column227", "column3": "column327", "column4": "column427", "column5": "column527", "column6": "column627", "column7": "column727", "column8": "column827", "column9": "column927"},
					{"column1": "column128", "column2": "column228", "column3": "column328", "column4": "column428", "column5": "column528", "column6": "column628", "column7": "column728", "column8": "column828", "column9": "column928"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var navigationBar_1 = new cpr.controls.NavigationBar();
			navigationBar_1.style.css({
				"background-color" : "aliceBlue",
				"background-image" : "none"
			});
			(function(navigationBar_1){
				navigationBar_1.addItem(new cpr.controls.MenuItem("label1", "value1", "root"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label2", "value2", "root"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label3", "value3", "root"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label4", "value4", "root"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label5", "value5", "root"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label6", "value6", "root"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label7", "value7", "value1"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label8", "value8", "value1"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label9", "value9", "value2"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label10", "value10", "value2"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label11", "value11", "value3"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label12", "value12", "value3"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label13", "value13", "value4"));
			})(navigationBar_1);
			container.addChild(navigationBar_1, {
				"top": "5px",
				"right": "5px",
				"left": "5px",
				"height": "40px"
			});
			
			var listBox_1 = new cpr.controls.ListBox("lbx1");
			listBox_1.style.css({
				"background-color" : "aliceBlue",
				"background-image" : "none"
			});
			(function(listBox_1){
				listBox_1.addItem(new cpr.controls.Item("label1", "value1"));
				listBox_1.addItem(new cpr.controls.Item("label2", "value2"));
				listBox_1.addItem(new cpr.controls.Item("label3", "value3"));
				listBox_1.addItem(new cpr.controls.Item("label4", "value4"));
				listBox_1.addItem(new cpr.controls.Item("label5", "value5"));
				listBox_1.addItem(new cpr.controls.Item("label6", "value6"));
				listBox_1.addItem(new cpr.controls.Item("label7", "value7"));
				listBox_1.addItem(new cpr.controls.Item("label8", "value8"));
				listBox_1.addItem(new cpr.controls.Item("label9", "value9"));
				listBox_1.addItem(new cpr.controls.Item("label10", "value10"));
				listBox_1.addItem(new cpr.controls.Item("label11", "value11"));
				listBox_1.addItem(new cpr.controls.Item("label12", "value12"));
				listBox_1.addItem(new cpr.controls.Item("label13", "value13"));
				listBox_1.addItem(new cpr.controls.Item("label14", "value14"));
				listBox_1.addItem(new cpr.controls.Item("label15", "value15"));
				listBox_1.addItem(new cpr.controls.Item("label16", "value16"));
				listBox_1.addItem(new cpr.controls.Item("label17", "value17"));
				listBox_1.addItem(new cpr.controls.Item("label18", "value18"));
				listBox_1.addItem(new cpr.controls.Item("label19", "value19"));
				listBox_1.addItem(new cpr.controls.Item("label20", "value20"));
			})(listBox_1);
			container.addChild(listBox_1, {
				"top": "50px",
				"bottom": "5px",
				"left": "5px",
				"width": "200px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.text = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.text = "column3";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.text = "column4";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.text = "column5";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.text = "column6";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.text = "column7";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.text = "column8";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.text = "column9";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "column4";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "column5";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.columnName = "column6";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.columnName = "column7";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.columnName = "column8";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.columnName = "column9";
							}
						}
					]
				}
			});
			grid_1.style.css({
				"background-color" : "aliceBlue",
				"background-image" : "none"
			});
			container.addChild(grid_1, {
				"top": "50px",
				"right": "5px",
				"bottom": "5px",
				"left": "210px"
			});
		}
	});
	app.title = "2-Menu";
	cpr.core.Platform.INSTANCE.register(app);
})();
