/*
 * App URI: 6-UDC/TimeTable
 * Source Location: 6-UDC/TimeTable.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("6-UDC/TimeTable", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/**
			 * @param {cpr.data.DataCollection}
			 *            ds
			 */
			function refresh(ds) {
				var rowIdx, eachData, eachOutput;
				var table = app.lookup("table");
			
				table.removeAllChildren(true);
			
				for (rowIdx = 0; rowIdx < ds.getRowCount(); rowIdx++) {
					eachData = ds.getRow(rowIdx).getRowData();
					eachOutput = new cpr.controls.Output();
					table.addChild(eachOutput, {
						left: (eachData.weekday / 7 * 100) + "%",
						top: (eachData.start * 10) + "%",
						width: (100 / 7) + "%",
						height: (eachData.end - eachData.start) * 10 + "%"
					});
					eachOutput.style.css({
						"background-color": eachData.color,
						'text-align': "center",
						"border-radius": "5px",
						"box-shadow": "0px 2px 5px gray"
					});
					eachOutput.value = eachData.text;
				}
			}
			
			function onBodyPropertyChange( /* cpr.events.CPropertyChangeEvent */ e) {
				if (e.property == "dataSet") {
					/** @type cpr.data.DataCollection */
					var newDataSet = e.newValue;
					if (newDataSet) {
						refresh(newDataSet);
					}
				} else {
					app.getContainer().redraw();
				}
			}
			
			function onBodyInit( /* cpr.events.CEvent */ e) {
				var ds1 = app.lookup("ds1");
				refresh(ds1);
			}
			// End - User Script
			
			// Header
			app.declareAppProperty("dataSet", null);
			app.declareBindableAppProperty("title", "Time Table");
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{
						"name": "weekday",
						"dataType": "number"
					},
					{
						"name": "start",
						"dataType": "number"
					},
					{
						"name": "end",
						"dataType": "number"
					},
					{
						"name": "text",
						"dataType": "string"
					},
					{"name": "color"}
				],
				"rows": [
					{"weekday": "1", "start": "1", "end": "2", "text": "text1", "color": "red"},
					{"weekday": "0", "start": "3", "end": "4", "text": "text2", "color": "orange"},
					{"weekday": "2", "start": "7", "end": "9", "text": "text3", "color": "blue"},
					{"weekday": "3", "start": "1", "end": "3", "text": "text4", "color": "magenta"},
					{"weekday": "5", "start": "4", "end": "7", "text": "text5", "color": "aliceblue"},
					{"weekday": "4", "start": "5", "end": "9", "text": "text6", "color": "cornflowerblue"},
					{"weekday": "6", "start": "3", "end": "6", "text": "text7", "color": "green"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("table");
			group_1.style.css({
				"border-right-style" : "solid",
				"background-size" : "100% 10%",
				"border-top-width" : "1px",
				"border-bottom-color" : "green",
				"border-right-width" : "1px",
				"border-left-color" : "green",
				"border-right-color" : "green",
				"border-left-width" : "1px",
				"border-top-style" : "solid",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-top-color" : "green",
				"border-bottom-style" : "solid",
				"background-image" : "linear-gradient(white calc(100% - 2px), silver calc(100% - 1px))"
			});
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
			})(group_1);
			container.addChild(group_1, {
				"top": "30px",
				"right": "0px",
				"bottom": "0px",
				"left": "0px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "제목";
			output_1.style.css({
				"text-align" : "center"
			});
			output_1.bind("value").toAppProperty("title");
			container.addChild(output_1, {
				"top": "0px",
				"right": "0px",
				"left": "0px",
				"height": "20px"
			});
			if(typeof onBodyPropertyChange == "function"){
				app.addEventListener("property-change", onBodyPropertyChange);
			}
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "TimeTable";
	cpr.core.Platform.INSTANCE.register(app);
})();
