/*
 * App URI: example/grid/grid_cellstyle
 * Source Location: example/grid/grid_cellstyle.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/grid/grid_cellstyle", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			function getProgressColor(/* Number */progress, /* Number */brightness) {
				progress = Math.min(Math.max(progress, 0), 100);
				return 'hsl(' + (232 - progress * 232).toFixed(0) + ", 100%, " + brightness + "%)";
			}
			
			/*
			 * Body에서 init 이벤트 발생 시 호출. 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit(/* cpr.events.CEvent */e) {
				// 함수를 등록합니다.
				cpr.expression.ExpressionEngine.INSTANCE.registerFunction("getProgressColor", getProgressColor);
				
				var progress = app.lookup("progress");
				progress.style.css({
					"background-repeat" : "no-repeat"
				});
				
				// 함수를 등록합니다.
				cpr.expression.ExpressionEngine.INSTANCE.registerFunction("getProgressColor", getProgressColor);
				
				progress.style.bind("background-image")
					.toExpression('"linear-gradient(" + getProgressColor(progressRate, 50) + ", " + getProgressColor(progressRate, 30) + ")"');
			
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			app.declareBindableAppProperty("explain", null);
			var dataSet_1 = new cpr.data.DataSet("sampleData");
			dataSet_1.parseData({
				"columns": [
					{
						"name": "val",
						"dataType": "number"
					},
					{
						"name": "progressRate",
						"dataType": "number"
					},
					{"name": "column3"}
				],
				"rows": [
					{"val": "1", "progressRate": "20", "column3": "column31"},
					{"val": "2", "progressRate": "40", "column3": "column32"},
					{"val": "3", "progressRate": "30", "column3": "column33"},
					{"val": "4", "progressRate": "50", "column3": "column34"},
					{"val": "5", "progressRate": "100", "column3": "column35"},
					{"val": "6", "progressRate": "70", "column3": "column36"},
					{"val": "7", "progressRate": "45", "column3": "column37"},
					{"val": "8", "progressRate": "12", "column3": "column38"},
					{"val": "9", "progressRate": "8", "column3": "column39"},
					{"val": "10", "progressRate": "84", "column3": "column310"},
					{"val": "11", "progressRate": "75", "column3": "column311"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("sampleData"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "진척도";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.text = "column3";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "progressRate";
								cell.control = (function(){
									var output_1 = new cpr.controls.Output("progress");
									output_1.value = "Output";
									output_1.style.bind("background-size").toExpression("progressRate + \"% 100%\"");
									output_1.bind("value").toDataColumn("progressRate");
									return output_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "70px",
				"right": "20px",
				"bottom": "20px",
				"left": "20px"
			});
			
			var userDefinedControl_1 = new udc.pagetitle2();
			userDefinedControl_1.bind("title").toAppProperty("title");
			userDefinedControl_1.bind("explain").toAppProperty("explain");
			container.addChild(userDefinedControl_1, {
				"top": "10px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "셀 스타일";
	cpr.core.Platform.INSTANCE.register(app);
})();
