/*
 * App URI: example/grid/grid_rowGroupClick
 * Source Location: example/grid/grid_rowGroupClick.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/grid/grid_rowGroupClick", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			/*
			 * 그리드에서 rowgroup-click 이벤트 발생 시 호출.
			 * Grid의 RowGroup 클릭시 발생하는 이벤트.
			 */
			function onGrd1RowgroupClick(/* cpr.events.CGridEvent */ e){
				/** 
				 * @type cpr.controls.Grid
				 */
				var grd1 = e.control;
				
				// 현재 rowgroup이 펼쳐져 있는지 유무를 반환합니다. (Grid 속성인 collapsible이 true일 때만 그룹을 collapse/expand 할 수 있습니다.)
				if(e.rowgroup.expanded){
					e.rowgroup.expanded = false;
				}else{
					e.rowgroup.expanded = true;
				}
				// 다음 기본 동작을 방지합니다. 
				// rowgroup-click 이벤트에서 한번 expand가 되고 기본이벤트로 collapse가 되어 expand가 안 되는 것처럼 보이는 현상을 막기 위해서 사용합니다.
				e.preventDefault();
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			app.declareBindableAppProperty("explain", null);
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "year"},
					{"name": "quarter"},
					{"name": "month"},
					{"name": "budget"},
					{"name": "expenditure"},
					{
						"name": "excess",
						"dataType": "expression",
						"displayOnly": true,
						"expression": "expenditure-budget"
					}
				],
				"rows": [
					{"year": "2016", "quarter": "1", "month": "1", "budget": "3000000", "expenditure": "4500000", "excess": "excess1"},
					{"year": "2016", "quarter": "1", "month": "2", "budget": "3220000", "expenditure": "3000000", "excess": "excess2"},
					{"year": "2016", "quarter": "1", "month": "3", "budget": "2000000", "expenditure": "2300000", "excess": "excess3"},
					{"year": "2016", "quarter": "2", "month": "4", "budget": "150000", "expenditure": "4500000", "excess": "excess4"},
					{"year": "2016", "quarter": "2", "month": "5", "budget": "4000000", "expenditure": "5000000", "excess": "excess5"},
					{"year": "2016", "quarter": "2", "month": "6", "budget": "1000000", "expenditure": "1200000", "excess": "excess6"},
					{"year": "2016", "quarter": "3", "month": "7", "budget": "1500000", "expenditure": "1560000", "excess": "excess7"},
					{"year": "2016", "quarter": "3", "month": "8", "budget": "3000000", "expenditure": "3200000", "excess": "excess8"},
					{"year": "2016", "quarter": "3", "month": "9", "budget": "4200000", "expenditure": "4600000", "excess": "excess9"},
					{"year": "2016", "quarter": "4", "month": "10", "budget": "2400000", "expenditure": "2300000", "excess": "excess10"},
					{"year": "2016", "quarter": "4", "month": "11", "budget": "2000000", "expenditure": "2300000", "excess": "excess11"},
					{"year": "2017", "quarter": "1", "month": "1", "budget": "3000000", "expenditure": "4500000", "excess": "excess12"},
					{"year": "2017", "quarter": "1", "month": "2", "budget": "3220000", "expenditure": "3000000", "excess": "excess13"},
					{"year": "2017", "quarter": "1", "month": "3", "budget": "2000000", "expenditure": "2300000", "excess": "excess14"},
					{"year": "2017", "quarter": "2", "month": "4", "budget": "150000", "expenditure": "4500000", "excess": "excess15"},
					{"year": "2017", "quarter": "2", "month": "5", "budget": "4000000", "expenditure": "5000000", "excess": "excess16"},
					{"year": "2017", "quarter": "2", "month": "6", "budget": "1000000", "expenditure": "1200000", "excess": "excess17"},
					{"year": "2017", "quarter": "3", "month": "7", "budget": "1500000", "expenditure": "1560000", "excess": "excess18"},
					{"year": "2017", "quarter": "3", "month": "8", "budget": "3000000", "expenditure": "3200000", "excess": "excess19"},
					{"year": "2017", "quarter": "3", "month": "9", "budget": "4200000", "expenditure": "4600000", "excess": "excess20"},
					{"year": "2017", "quarter": "4", "month": "10", "budget": "2400000", "expenditure": "2300000", "excess": "excess21"},
					{"year": "2017", "quarter": "4", "month": "11", "budget": "2000000", "expenditure": "2300000", "excess": "excess22"},
					{"year": "2018", "quarter": "1", "month": "1", "budget": "3000000", "expenditure": "4500000", "excess": "excess23"},
					{"year": "2018", "quarter": "1", "month": "2", "budget": "3220000", "expenditure": "3000000", "excess": "excess24"},
					{"year": "2018", "quarter": "1", "month": "3", "budget": "2000000", "expenditure": "2300000", "excess": "excess25"},
					{"year": "2018", "quarter": "2", "month": "4", "budget": "150000", "expenditure": "4500000", "excess": "excess26"},
					{"year": "2018", "quarter": "2", "month": "5", "budget": "4000000", "expenditure": "5000000", "excess": "excess27"},
					{"year": "2018", "quarter": "2", "month": "6", "budget": "1000000", "expenditure": "1200000", "excess": "excess28"},
					{"year": "2018", "quarter": "3", "month": "7", "budget": "1500000", "expenditure": "1560000", "excess": "excess29"},
					{"year": "2018", "quarter": "3", "month": "8", "budget": "3000000", "expenditure": "3200000", "excess": "excess30"},
					{"year": "2018", "quarter": "3", "month": "9", "budget": "4200000", "expenditure": "4600000", "excess": "excess31"},
					{"year": "2018", "quarter": "4", "month": "10", "budget": "2400000", "expenditure": "2300000", "excess": "excess32"},
					{"year": "2018", "quarter": "4", "month": "11", "budget": "2000000", "expenditure": "2300000", "excess": "excess33"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 800px) and (max-width: 1023px)", "new-screen");
			app.supportMedia("all and (min-width: 500px) and (max-width: 799px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"selectionMulti": "multi",
				"showDeletedRow": false,
				"collapsible": true,
				"columns": [
					{"width": "30px"},
					{"width": "30px"},
					{"width": "60px"},
					{"width": "60px"},
					{"width": "60px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.sortColumnName = "year";
								cell.text = "년도";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.sortColumnName = "quarter";
								cell.text = "분기";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.sortColumnName = "month";
								cell.text = "월";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.sortColumnName = "budget";
								cell.text = "예산";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.sortColumnName = "expenditure";
								cell.text = "지출";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.sortColumnName = "excess";
								cell.text = "초과액";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "year";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "quarter";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "month";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.columnName = "budget";
								cell.control = (function(){
									var numberEditor_1 = new cpr.controls.NumberEditor("nbe1");
									numberEditor_1.format = "s000,000,000,000";
									numberEditor_1.bind("value").toDataColumn("budget");
									return numberEditor_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.columnName = "expenditure";
								cell.control = (function(){
									var numberEditor_2 = new cpr.controls.NumberEditor("nbe2");
									numberEditor_2.format = "s000,000,000,000";
									numberEditor_2.bind("value").toDataColumn("expenditure");
									return numberEditor_2;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.columnName = "excess";
								cell.control = (function(){
									var numberEditor_3 = new cpr.controls.NumberEditor("nbe3");
									numberEditor_3.format = "s000,000,000,000";
									numberEditor_3.bind("value").toDataColumn("excess");
									return numberEditor_3;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnType = "checkbox";
								cell.style.css({
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnType = "rowindex";
								cell.style.css({
									"text-align" : "center"
								});
							}
						}
					]
				},
				"footer": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.expr = "getSum('budget')";
								cell.control = (function(){
									var userDefinedControl_1 = new udc.currencyLabel();
									return userDefinedControl_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.expr = "getSum('expenditure')";
								cell.control = (function(){
									var userDefinedControl_2 = new udc.currencyLabel();
									return userDefinedControl_2;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.expr = "getSum('excess')";
								cell.control = (function(){
									var userDefinedControl_3 = new udc.currencyLabel();
									return userDefinedControl_3;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 5},
							"configurator": function(cell){
								cell.expr = "";
							}
						}
					]
				},
				"rowGroup": [{
					"groupCondition": "year",
					"gheader": {
						"rows": [{"height": "24px"}],
						"cells": [{
							"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 8},
							"configurator": function(cell){
								cell.expr = "year +'년도 ' + month + '월'";
								cell.style.css({
									"text-align" : "center"
								});
							}
						}]
					},
					"gfooter": {
						"rows": [{"height": "30px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.expr = "getSum('budget')";
									cell.style.css({
										"text-align" : "right"
									});
									cell.control = (function(){
										var numberEditor_4 = new cpr.controls.NumberEditor("nbe4");
										numberEditor_4.format = "s000,000,000,000";
										return numberEditor_4;
									})();
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.expr = "getSum('expenditure')";
									cell.style.css({
										"text-align" : "right"
									});
									cell.control = (function(){
										var numberEditor_5 = new cpr.controls.NumberEditor("nbe5");
										numberEditor_5.format = "s000,000,000,000";
										return numberEditor_5;
									})();
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.expr = "getSum('excess')";
									cell.style.css({
										"text-align" : "right"
									});
									cell.control = (function(){
										var numberEditor_6 = new cpr.controls.NumberEditor("nbe6");
										numberEditor_6.format = "s000,000,000,000";
										return numberEditor_6;
									})();
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 5},
								"configurator": function(cell){
									cell.expr = "";
								}
							}
						]
					}
				}]
			});
			if(typeof onGrd1RowgroupClick == "function") {
				grid_1.addEventListener("rowgroup-click", onGrd1RowgroupClick);
			}
			container.addChild(grid_1, {
				"top": "70px",
				"right": "10px",
				"bottom": "10px",
				"left": "10px"
			});
			
			var userDefinedControl_4 = new udc.pagetitle2();
			userDefinedControl_4.bind("title").toAppProperty("title");
			userDefinedControl_4.bind("explain").toAppProperty("explain");
			container.addChild(userDefinedControl_4, {
				"top": "10px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
		}
	});
	app.title = "grid_rowGroupClick";
	cpr.core.Platform.INSTANCE.register(app);
})();
