/*
 * App URI: 0-basic/1-GridContextBind
 * Source Location: 0-basic/1-GridContextBind.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("0-basic/1-GridContextBind", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * GridContextBind.js
			 * Created at 2018. 9. 10. 오전 10:32:59.
			 *
			 * @author ryu
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "id"},
					{"name": "name"},
					{
						"name": "age",
						"dataType": "number"
					},
					{"name": "phone"},
					{"name": "email"}
				],
				"rows": [
					{"id": "123", "name": "Ann", "age": "20", "phone": "010-0000-0000", "email": "ann@abc.com"},
					{"id": "456", "name": "Jack", "age": "17", "phone": "010-1111-1111", "email": "jack@abc.net"},
					{"id": "789", "name": "Smith", "age": "18", "phone": "010-2222-2222", "email": "smith12@abc.com"},
					{"id": "012", "name": "Jin", "age": "20", "phone": "010-3333-3333", "email": "jiny@abc.net"},
					{"id": "345", "name": "Mike", "age": "15", "phone": "010-4444-4444", "email": "mike@abc.com"},
					{"id": "678", "name": "Zach", "age": "28", "phone": "010-5555-5555", "email": "zach@abc.net"},
					{"id": "901", "name": "Brock", "age": "30", "phone": "010-6666-6666", "email": "brock@abc.com"},
					{"id": "234", "name": "Dean", "age": "41", "phone": "010-7777-7777", "email": "dean@def.com"},
					{"id": "567", "name": "Sam", "age": "32", "phone": "010-8888-8888", "email": "sam@def.com"},
					{"id": "890", "name": "Alex", "age": "25", "phone": "010-9999-9999", "email": "alex@def.net"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = linker.grid_1 = new cpr.controls.Grid("grd1");
			grid_1.readOnly = true;
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columnMovable": false,
				"columnResizable": false,
				"columns": [
					{"width": "25px"},
					{"width": "50px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.columnType = "checkbox";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.targetColumnName = "column1";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "id";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.targetColumnName = "column2";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "name";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.targetColumnName = "column3";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "age";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.targetColumnName = "column4";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "phone";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.targetColumnName = "column5";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "email";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnType = "checkbox";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnType = "rowindex";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "id";
								cell.control = (function(){
									var inputBox_1 = new cpr.controls.InputBox("ipb1");
									inputBox_1.bind("value").toDataColumn("id");
									return inputBox_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "name";
								cell.control = (function(){
									var inputBox_2 = new cpr.controls.InputBox("ipb2");
									inputBox_2.bind("value").toDataColumn("name");
									return inputBox_2;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "age";
								cell.control = (function(){
									var inputBox_3 = new cpr.controls.InputBox("ipb3");
									inputBox_3.bind("value").toDataColumn("age");
									return inputBox_3;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.columnName = "phone";
								cell.control = (function(){
									var inputBox_4 = new cpr.controls.InputBox("ipb4");
									inputBox_4.bind("value").toDataColumn("phone");
									return inputBox_4;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.columnName = "email";
								cell.control = (function(){
									var inputBox_5 = new cpr.controls.InputBox("ipb5");
									inputBox_5.bind("value").toDataColumn("email");
									return inputBox_5;
								})();
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "20px",
				"bottom": "20px",
				"left": "20px",
				"width": "600px"
			});
			
			var group_1 = linker.group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.setColumns(["100px", "1fr"]);
			formLayout_1.setUseColumnShade(0, true);
			formLayout_1.setRows(["25px", "25px", "25px", "25px", "1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "id";
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "name";
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "age";
				container.addChild(output_3, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "phone";
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "email";
				container.addChild(output_5, {
					"colIndex": 0,
					"rowIndex": 4
				});
				var inputBox_6 = new cpr.controls.InputBox("ipb6");
				inputBox_6.bind("value").toDataColumn("id");
				container.addChild(inputBox_6, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var inputBox_7 = new cpr.controls.InputBox("ipb7");
				inputBox_7.bind("value").toDataColumn("name");
				container.addChild(inputBox_7, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var inputBox_8 = new cpr.controls.InputBox("ipb8");
				inputBox_8.bind("value").toDataColumn("age");
				container.addChild(inputBox_8, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var inputBox_9 = new cpr.controls.InputBox("ipb9");
				inputBox_9.bind("value").toDataColumn("phone");
				container.addChild(inputBox_9, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var textArea_1 = new cpr.controls.TextArea("txa1");
				textArea_1.bind("value").toDataColumn("email");
				container.addChild(textArea_1, {
					"colIndex": 1,
					"rowIndex": 4
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "20px",
				"right": "20px",
				"bottom": "20px",
				"left": "630px"
			});
			// Linking
			linker.group_1.setBindContext(new cpr.bind.GridSelectionContext(linker.grid_1));
		}
	});
	app.title = "1-GridContextBind";
	cpr.core.Platform.INSTANCE.register(app);
})();
