/*
 * App URI: 6-UDC/bomb/BombButton
 * Source Location: 6-UDC/bomb/BombButton.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("6-UDC/bomb/BombButton", {
		onPrepare: function(loader){
			loader.addCSS("6-UDC/bomb/bomb.css");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			var leftTick = 10;
			
			function onButtonCick( /* cpr.events.CMouseEvent */ e) {
				if (leftTick <= 0) {
					return;
				}
			
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				var progress = app.lookup("progress");
				progress.value = String(--leftTick);
			
				if (leftTick == 0) {
					var bombEvent = new cpr.events.CUIEvent("bomb");
					if(app.dispatchEvent(bombEvent)){
						var explosion = new cpr.controls.Output();
						explosion.style.setClasses("explosion");
						
						app.getRootAppInstance().floatControl(explosion);
						
						setTimeout(function(){
							explosion.dispose();
						}, 1000);
					}
				}
			}
			
			/**
			 * Resets the state of the progress bar.
			 */
			exports.reset = function() {
				leftTick = 10;
				var progress = app.lookup("progress");
				progress.value = String(leftTick);
			};
			
			function onBodyPropertyChange( /* cpr.events.CPropertyChangeEvent */ e) {
				app.getContainer().redraw();
			}
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("buttonTitle", "tick");
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var progress_1 = new cpr.controls.Progress("progress");
			progress_1.value = "10";
			progress_1.max = 10.0;
			progress_1.style.setClasses(["bomb"]);
			container.addChild(progress_1, {
				"right": "110px",
				"left": "0px",
				"height": "30px",
				"top": "calc(50% - 15px)"
			});
			
			var button_1 = new cpr.controls.Button();
			button_1.value = "째깍째깍";
			button_1.bind("value").toAppProperty("buttonTitle");
			if(typeof onButtonCick == "function") {
				button_1.addEventListener("click", onButtonCick);
			}
			container.addChild(button_1, {
				"top": "0px",
				"right": "0px",
				"bottom": "0px",
				"width": "100px"
			});
			if(typeof onBodyPropertyChange == "function"){
				app.addEventListener("property-change", onBodyPropertyChange);
			}
		}
	});
	app.title = "BombButton";
	cpr.core.Platform.INSTANCE.register(app);
})();
