/*
 * App URI: example/component/maskformat
 * Source Location: example/component/maskformat.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/component/maskformat", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			/*
			 * 데이트 인풋에서 value-change 이벤트 발생 시 호출.
			 * Dateinput의 value를 변경하여 변경된 값이 저장된 후에 발생하는 이벤트.
			 */
			function onDti1ValueChange(/* cpr.events.CValueChangeEvent */ e){
				/** 
				 * @type cpr.controls.DateInput
				 */
				var control = e.control;
				
				// 화면 전체를 redraw 합니다.
				app.getContainer().redraw();
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			app.declareBindableAppProperty("explain", null);
			var dataMap_1 = new cpr.data.DataMap("resKey");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "20171204"
					},
					{
						"name": "column2",
						"defaultValue": "20170101"
					},
					{
						"name": "column3",
						"defaultValue": "20170315053025"
					},
					{
						"name": "column4",
						"defaultValue": "60"
					},
					{
						"name": "column5",
						"defaultValue": "1000"
					},
					{
						"name": "column6",
						"defaultValue": "01234.56780"
					},
					{
						"name": "column7",
						"defaultValue": "2348301453"
					},
					{
						"name": "column8",
						"defaultValue": "1234567891023456"
					},
					{
						"name": "column9",
						"defaultValue": "hello!!!"
					},
					{
						"name": "column10",
						"defaultValue": "12fd4"
					},
					{
						"name": "column11",
						"defaultValue": "입력하세요!"
					},
					{
						"name": "column12",
						"defaultValue": "2018"
					},
					{
						"name": "column13",
						"defaultValue": "201801"
					}
				]
			});
			app.register(dataMap_1);
			
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp_frm");
			var dataMapContext_1 = new cpr.bind.DataMapContext(app.lookup("resKey"));
			group_1.setBindContext(dataMapContext_1);
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.horizontalSeparatorClass = "frm-hseparator";
			formLayout_1.horizontalSeparatorWidth = 1;
			formLayout_1.verticalSeparatorClass = "frm-vseparator";
			formLayout_1.verticalSeparatorWidth = 1;
			formLayout_1.setColumns(["100px", "70px", "100px", "1fr", "1fr"]);
			formLayout_1.setRows(["25px", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "분류";
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0,
					"colSpan": 3,
					"rowSpan": 1
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "컨트롤";
				container.addChild(output_2, {
					"colIndex": 3,
					"rowIndex": 0
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "값";
				container.addChild(output_3, {
					"colIndex": 4,
					"rowIndex": 0
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "날짜";
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 1,
					"colSpan": 1,
					"rowSpan": 5
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "숫자";
				container.addChild(output_5, {
					"colIndex": 0,
					"rowIndex": 6,
					"colSpan": 1,
					"rowSpan": 3
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "마스킹";
				container.addChild(output_6, {
					"colIndex": 0,
					"rowIndex": 9,
					"colSpan": 1,
					"rowSpan": 2
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "필터";
				container.addChild(output_7, {
					"colIndex": 0,
					"rowIndex": 11,
					"colSpan": 1,
					"rowSpan": 2
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "최소/최대\r\n(2017-12-01 ~ 2017-12-31)";
				container.addChild(output_8, {
					"colIndex": 1,
					"rowIndex": 1,
					"colSpan": 2,
					"rowSpan": 1,
					"verticalAlign": "fill"
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = "형식\r\n(mask)";
				container.addChild(output_9, {
					"colIndex": 1,
					"rowIndex": 2,
					"colSpan": 1,
					"rowSpan": 4,
					"verticalAlign": "fill"
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "최대/최소\r\n(-100 ~ 100)";
				container.addChild(output_10, {
					"colIndex": 1,
					"rowIndex": 6,
					"colSpan": 2,
					"rowSpan": 1,
					"verticalAlign": "fill"
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = "형식\r\n(format)";
				container.addChild(output_11, {
					"colIndex": 1,
					"rowIndex": 7,
					"colSpan": 1,
					"rowSpan": 2,
					"verticalAlign": "fill"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "바이트 최대 길이";
				container.addChild(output_12, {
					"colIndex": 0,
					"rowIndex": 13
				});
				var output_13 = new cpr.controls.Output();
				output_13.value = "date\r\n(YYYY-MM-DD)";
				container.addChild(output_13, {
					"colIndex": 2,
					"rowIndex": 2
				});
				var output_14 = new cpr.controls.Output();
				output_14.value = "datetime\r\n(YYYY-MM-DD HH:mm:ss)";
				container.addChild(output_14, {
					"colIndex": 2,
					"rowIndex": 3
				});
				var output_15 = new cpr.controls.Output();
				output_15.value = "integer\r\n(s00000)";
				container.addChild(output_15, {
					"colIndex": 2,
					"rowIndex": 7
				});
				var output_16 = new cpr.controls.Output();
				output_16.value = "float\r\n(s00000.99999)";
				container.addChild(output_16, {
					"colIndex": 2,
					"rowIndex": 8,
					"colSpan": 1,
					"rowSpan": 1
				});
				var output_17 = new cpr.controls.Output();
				output_17.value = "사업자등록번호\r\n(000-00-00000)";
				container.addChild(output_17, {
					"colIndex": 1,
					"rowIndex": 9,
					"colSpan": 2,
					"rowSpan": 1
				});
				var output_18 = new cpr.controls.Output();
				output_18.value = "카드 mask\r\n(0000-0000-0000-0000)";
				container.addChild(output_18, {
					"colIndex": 1,
					"rowIndex": 10,
					"colSpan": 2,
					"rowSpan": 1
				});
				var output_19 = new cpr.controls.Output();
				output_19.value = "형식\r\n(inputFilter)";
				container.addChild(output_19, {
					"colIndex": 1,
					"rowIndex": 11,
					"colSpan": 1,
					"rowSpan": 2
				});
				var output_20 = new cpr.controls.Output();
				output_20.value = "alphabetic\r\n([a-zA-Z])";
				container.addChild(output_20, {
					"colIndex": 2,
					"rowIndex": 11
				});
				var output_21 = new cpr.controls.Output();
				output_21.value = "hexa\r\n([0-9a-fA-F])";
				container.addChild(output_21, {
					"colIndex": 2,
					"rowIndex": 12
				});
				var output_22 = new cpr.controls.Output();
				output_22.value = "lengthUnit / MaxLength\r\n(utf8 / 10)";
				container.addChild(output_22, {
					"colIndex": 1,
					"rowIndex": 13,
					"colSpan": 2,
					"rowSpan": 1
				});
				var dateInput_1 = new cpr.controls.DateInput("dti1");
				dateInput_1.minDate = new Date(2017, 11, 1);
				dateInput_1.maxDate = new Date(2017, 11, 31);
				dateInput_1.autoSelect = true;
				dateInput_1.bind("value").toDataColumn("column1");
				if(typeof onDti1ValueChange == "function") {
					dateInput_1.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(dateInput_1, {
					"colIndex": 3,
					"rowIndex": 1
				});
				var output_23 = new cpr.controls.Output();
				output_23.value = "";
				output_23.bind("value").toDataColumn("column1");
				container.addChild(output_23, {
					"colIndex": 4,
					"rowIndex": 1
				});
				var dateInput_2 = new cpr.controls.DateInput("dti2");
				dateInput_2.autoSelect = true;
				dateInput_2.bind("value").toDataColumn("column2");
				if(typeof onDti1ValueChange == "function") {
					dateInput_2.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(dateInput_2, {
					"colIndex": 3,
					"rowIndex": 2
				});
				var output_24 = new cpr.controls.Output();
				output_24.value = "";
				output_24.bind("value").toDataColumn("column2");
				container.addChild(output_24, {
					"colIndex": 4,
					"rowIndex": 2
				});
				var dateInput_3 = new cpr.controls.DateInput("dti3");
				dateInput_3.hideButton = true;
				dateInput_3.mask = "YYYY-MM-DD HH:mm:ss";
				dateInput_3.format = "YYYYMMDDHHmmss";
				dateInput_3.autoSelect = true;
				dateInput_3.bind("value").toDataColumn("column3");
				if(typeof onDti1ValueChange == "function") {
					dateInput_3.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(dateInput_3, {
					"colIndex": 3,
					"rowIndex": 3
				});
				var output_25 = new cpr.controls.Output();
				output_25.value = "";
				output_25.bind("value").toDataColumn("column3");
				container.addChild(output_25, {
					"colIndex": 4,
					"rowIndex": 3
				});
				var dateInput_4 = new cpr.controls.DateInput("dti4");
				dateInput_4.maxDate = new Date(2099, 11, 31);
				dateInput_4.calendarType = "year";
				dateInput_4.mask = "YYYY";
				dateInput_4.format = "YYYY";
				dateInput_4.autoSelect = true;
				dateInput_4.bind("value").toDataColumn("column12");
				if(typeof onDti1ValueChange == "function") {
					dateInput_4.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(dateInput_4, {
					"colIndex": 3,
					"rowIndex": 4
				});
				var dateInput_5 = new cpr.controls.DateInput("dti5");
				dateInput_5.calendarType = "yearmonth";
				dateInput_5.mask = "YYYY-MM";
				dateInput_5.format = "YYYYMM";
				dateInput_5.autoSelect = true;
				dateInput_5.bind("value").toDataColumn("column13");
				if(typeof onDti1ValueChange == "function") {
					dateInput_5.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(dateInput_5, {
					"colIndex": 3,
					"rowIndex": 5
				});
				var numberEditor_1 = new cpr.controls.NumberEditor("nbe1");
				numberEditor_1.min = -100.0;
				numberEditor_1.max = 100.0;
				numberEditor_1.format = "s000";
				numberEditor_1.autoSelect = true;
				numberEditor_1.bind("value").toDataColumn("column4");
				if(typeof onDti1ValueChange == "function") {
					numberEditor_1.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(numberEditor_1, {
					"colIndex": 3,
					"rowIndex": 6
				});
				var output_26 = new cpr.controls.Output();
				output_26.value = "";
				output_26.bind("value").toDataColumn("column4");
				container.addChild(output_26, {
					"colIndex": 4,
					"rowIndex": 6
				});
				var numberEditor_2 = new cpr.controls.NumberEditor("nbe2");
				numberEditor_2.format = "s00000";
				numberEditor_2.autoSelect = true;
				numberEditor_2.bind("value").toDataColumn("column5");
				if(typeof onDti1ValueChange == "function") {
					numberEditor_2.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(numberEditor_2, {
					"colIndex": 3,
					"rowIndex": 7
				});
				var output_27 = new cpr.controls.Output();
				output_27.value = "";
				output_27.bind("value").toDataColumn("column5");
				container.addChild(output_27, {
					"colIndex": 4,
					"rowIndex": 7
				});
				var numberEditor_3 = new cpr.controls.NumberEditor("nbe3");
				numberEditor_3.step = 1.0E-5;
				numberEditor_3.format = "s00000.99999";
				numberEditor_3.autoSelect = true;
				numberEditor_3.bind("value").toDataColumn("column6");
				if(typeof onDti1ValueChange == "function") {
					numberEditor_3.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(numberEditor_3, {
					"colIndex": 3,
					"rowIndex": 8,
					"colSpan": 1,
					"rowSpan": 1
				});
				var output_28 = new cpr.controls.Output();
				output_28.value = "";
				output_28.bind("value").toDataColumn("column6");
				container.addChild(output_28, {
					"colIndex": 4,
					"rowIndex": 8
				});
				var output_29 = new cpr.controls.Output();
				output_29.value = "";
				output_29.bind("value").toDataColumn("column7");
				container.addChild(output_29, {
					"colIndex": 4,
					"rowIndex": 9
				});
				var output_30 = new cpr.controls.Output();
				output_30.value = "";
				output_30.bind("value").toDataColumn("column8");
				container.addChild(output_30, {
					"colIndex": 4,
					"rowIndex": 10
				});
				var output_31 = new cpr.controls.Output();
				output_31.value = "";
				output_31.bind("value").toDataColumn("column9");
				container.addChild(output_31, {
					"colIndex": 4,
					"rowIndex": 11
				});
				var output_32 = new cpr.controls.Output();
				output_32.value = "";
				output_32.bind("value").toDataColumn("column10");
				container.addChild(output_32, {
					"colIndex": 4,
					"rowIndex": 12
				});
				var output_33 = new cpr.controls.Output();
				output_33.value = "";
				output_33.bind("value").toDataColumn("column11");
				container.addChild(output_33, {
					"colIndex": 4,
					"rowIndex": 13
				});
				var maskEditor_1 = new cpr.controls.MaskEditor("mse2");
				maskEditor_1.mask = "000-00-00000";
				maskEditor_1.autoSelect = true;
				maskEditor_1.bind("value").toDataColumn("column7");
				container.addChild(maskEditor_1, {
					"colIndex": 3,
					"rowIndex": 9
				});
				var maskEditor_2 = new cpr.controls.MaskEditor("mse1");
				maskEditor_2.mask = "0000-0000-0000-0000";
				maskEditor_2.autoSelect = true;
				maskEditor_2.bind("value").toDataColumn("column8");
				if(typeof onDti1ValueChange == "function") {
					maskEditor_2.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(maskEditor_2, {
					"colIndex": 3,
					"rowIndex": 10
				});
				var inputBox_1 = new cpr.controls.InputBox("ipb1");
				inputBox_1.autoSelect = true;
				inputBox_1.inputFilter = "[a-zA-Z]";
				inputBox_1.bind("value").toDataColumn("column9");
				if(typeof onDti1ValueChange == "function") {
					inputBox_1.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(inputBox_1, {
					"colIndex": 3,
					"rowIndex": 11
				});
				var inputBox_2 = new cpr.controls.InputBox("ipb2");
				inputBox_2.autoSelect = true;
				inputBox_2.inputFilter = "[0-9a-fA-F]";
				inputBox_2.bind("value").toDataColumn("column10");
				if(typeof onDti1ValueChange == "function") {
					inputBox_2.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(inputBox_2, {
					"colIndex": 3,
					"rowIndex": 12
				});
				var inputBox_3 = new cpr.controls.InputBox("ipb3");
				inputBox_3.lengthUnit = "utf8";
				inputBox_3.maxLength = 10;
				inputBox_3.autoSelect = true;
				inputBox_3.bind("value").toDataColumn("column11");
				if(typeof onDti1ValueChange == "function") {
					inputBox_3.addEventListener("value-change", onDti1ValueChange);
				}
				container.addChild(inputBox_3, {
					"colIndex": 3,
					"rowIndex": 13
				});
				var output_34 = new cpr.controls.Output();
				output_34.value = "연도";
				container.addChild(output_34, {
					"colIndex": 2,
					"rowIndex": 4
				});
				var output_35 = new cpr.controls.Output();
				output_35.value = "월";
				container.addChild(output_35, {
					"colIndex": 2,
					"rowIndex": 5
				});
				var output_36 = new cpr.controls.Output();
				output_36.value = "Output";
				output_36.bind("value").toDataColumn("column12");
				container.addChild(output_36, {
					"colIndex": 4,
					"rowIndex": 4
				});
				var output_37 = new cpr.controls.Output();
				output_37.value = "Output";
				output_37.bind("value").toDataColumn("column13");
				container.addChild(output_37, {
					"colIndex": 4,
					"rowIndex": 5
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "70px",
				"right": "10px",
				"bottom": "10px",
				"left": "10px"
			});
			
			var userDefinedControl_1 = new udc.pagetitle2();
			userDefinedControl_1.bind("title").toAppProperty("title");
			userDefinedControl_1.bind("explain").toAppProperty("explain");
			container.addChild(userDefinedControl_1, {
				"top": "10px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
		}
	});
	app.title = "maskformat";
	cpr.core.Platform.INSTANCE.register(app);
})();
