/*
 * App URI: example/component/nav_megamenu
 * Source Location: example/component/nav_megamenu.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/component/nav_megamenu", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			function convertRadioValue(value){
				if(typeof value == "string"){
					if(value == "true"){
						return true;
					}else if(value == "false"){
						return false;
					}
				}
				return value;
			}
			/*
			 * "Apply" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				var id = "col2_"+btn1.userattr("index");
				var property = btn1.userattr("property");
				var control = app.lookup(id);
				var nav = app.lookup("nav1");
				if(control.type == "radiobutton"){
					nav[property] = convertRadioValue(control.value);
				}else{
					nav[property] = control.value;
				}
				
			}
			/*
			 * "execute" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(/* cpr.events.CMouseEvent */ e){
				
				var txa = app.lookup("txa1");
				eval(txa.value);
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			app.declareBindableAppProperty("explain", null);
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"},
					{"name": "pValue"}
				],
				"rows": [
					{"label": "서울", "value": "001", "pValue": "root"},
					{"label": "대전", "value": "002", "pValue": "root"},
					{"label": "대구", "value": "003", "pValue": "root"},
					{"label": "부산", "value": "004", "pValue": "root"},
					{"label": "1호선", "value": "00101", "pValue": "001"},
					{"label": "2호선", "value": "00102", "pValue": "001"},
					{"label": "3호선", "value": "00103", "pValue": "001"},
					{"label": "4호선", "value": "00104", "pValue": "001"},
					{"label": "5호선", "value": "00105", "pValue": "001"},
					{"label": "6호선", "value": "00106", "pValue": "001"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("radio");
			dataSet_2.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"}
				],
				"rows": [
					{"label": "true", "value": "true"},
					{"label": "false", "value": "false"}
				]
			});
			app.register(dataSet_2);
			var dataMap_1 = new cpr.data.DataMap("dm1");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "column1",
						"dataType": "string",
						"defaultValue": "1"
					},
					{
						"name": "column2",
						"defaultValue": "2"
					},
					{
						"name": "column3",
						"defaultValue": "3"
					},
					{
						"name": "column4",
						"defaultValue": "4"
					},
					{
						"name": "column5",
						"defaultValue": "5"
					}
				]
			});
			app.register(dataMap_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var navigationBar_1 = new cpr.controls.NavigationBar("nav1");
			navigationBar_1.menuType = "megamenu";
			(function(navigationBar_1){
				navigationBar_1.addItem(new cpr.controls.MenuItem("신도림", "0010101", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("서울역", "0010102", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("강남역", "0010201", "00102"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("잠실역", "0010202", "00102"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("남부터미널역", "0010301", "00103"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("서초역", "0010302", "00103"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("이수역", "0010401", "00104"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("사당역", "0010402", "00104"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("시청역", "0010103", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("용산역", "0010104", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("영등포역", "0010105", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("노량진역", "0010106", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("을지로역", "0010107", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("종로5가역", "0010108", "00101"));
				navigationBar_1.addItem(new cpr.controls.MenuItem("종로3가역", "0010109", "00101"));
				navigationBar_1.setItemSet(app.lookup("ds1"), {
					"label": "label",
					"value": "value",
					"icon": "",
					"parentValue": "pValue"
				});
			})(navigationBar_1);
			container.addChild(navigationBar_1, {
				"top": "78px",
				"right": "10px",
				"left": "10px",
				"height": "40px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"border-bottom-color" : "#ebebeb",
				"border-right-width" : "1px",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-left-color" : "#ebebeb",
				"border-top-color" : "#ebebeb",
				"border-bottom-style" : "solid",
				"border-right-color" : "#ebebeb",
				"border-left-width" : "1px",
				"border-top-style" : "solid"
			});
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.topMargin = "5";
			formLayout_1.rightMargin = "5";
			formLayout_1.bottomMargin = "5";
			formLayout_1.leftMargin = "5";
			formLayout_1.horizontalSpacing = "10";
			formLayout_1.verticalSpacing = "10";
			formLayout_1.horizontalSeparatorWidth = 1;
			formLayout_1.verticalSeparatorWidth = 1;
			formLayout_1.setColumns(["120px", "1fr", "100px"]);
			formLayout_1.setUseColumnShade(0, true);
			formLayout_1.setRows(["25px", "25px", "25px", "25px", "25px", "25px", "25px", "25px", "25px"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var button_1 = new cpr.controls.Button();
				button_1.value = "Apply";
				button_1.userAttr({
					"index": "1",
					"property": "enabled"
				});
				if(typeof onBtn1Click == "function") {
					button_1.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_1, {
					"colIndex": 2,
					"rowIndex": 0
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "Apply";
				button_2.userAttr({
					"index": "2",
					"property": "tooltip"
				});
				if(typeof onBtn1Click == "function") {
					button_2.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_2, {
					"colIndex": 2,
					"rowIndex": 1
				});
				var button_3 = new cpr.controls.Button();
				button_3.value = "Apply";
				button_3.userAttr({
					"index": "3",
					"property": "visible"
				});
				if(typeof onBtn1Click == "function") {
					button_3.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_3, {
					"colIndex": 2,
					"rowIndex": 2
				});
				var button_4 = new cpr.controls.Button();
				button_4.value = "Apply";
				button_4.userAttr({
					"index": "4",
					"property": "barArrowImage"
				});
				if(typeof onBtn1Click == "function") {
					button_4.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_4, {
					"colIndex": 2,
					"rowIndex": 3
				});
				var button_5 = new cpr.controls.Button();
				button_5.value = "Apply";
				button_5.userAttr({
					"index": "5",
					"property": "displayExp"
				});
				if(typeof onBtn1Click == "function") {
					button_5.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_5, {
					"colIndex": 2,
					"rowIndex": 4
				});
				var button_6 = new cpr.controls.Button();
				button_6.value = "Apply";
				button_6.userAttr({
					"index": "6",
					"property": "listArrowImage"
				});
				if(typeof onBtn1Click == "function") {
					button_6.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_6, {
					"colIndex": 2,
					"rowIndex": 5
				});
				var button_7 = new cpr.controls.Button();
				button_7.value = "Apply";
				button_7.userAttr({
					"index": "7",
					"property": "readOnly"
				});
				if(typeof onBtn1Click == "function") {
					button_7.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_7, {
					"colIndex": 2,
					"rowIndex": 6
				});
				var button_8 = new cpr.controls.Button();
				button_8.value = "Apply";
				button_8.userAttr({
					"index": "8",
					"property": "value"
				});
				if(typeof onBtn1Click == "function") {
					button_8.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_8, {
					"colIndex": 2,
					"rowIndex": 7
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "enabled";
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "tooltip";
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "visible";
				container.addChild(output_3, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "barArrowImage";
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "displayExp";
				container.addChild(output_5, {
					"colIndex": 0,
					"rowIndex": 4
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "listArrowImage";
				container.addChild(output_6, {
					"colIndex": 0,
					"rowIndex": 5
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "readOnly";
				container.addChild(output_7, {
					"colIndex": 0,
					"rowIndex": 6
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "value";
				container.addChild(output_8, {
					"colIndex": 0,
					"rowIndex": 7
				});
				var radioButton_1 = new cpr.controls.RadioButton("col2_1");
				radioButton_1.value = "true";
				(function(radioButton_1){
					radioButton_1.setItemSet(app.lookup("radio"), {
						"label": "label",
						"value": "value"
					})
				})(radioButton_1);
				container.addChild(radioButton_1, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var radioButton_2 = new cpr.controls.RadioButton("col2_3");
				radioButton_2.value = "true";
				(function(radioButton_2){
					radioButton_2.setItemSet(app.lookup("radio"), {
						"label": "label",
						"value": "value"
					})
				})(radioButton_2);
				container.addChild(radioButton_2, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var radioButton_3 = new cpr.controls.RadioButton("col2_7");
				radioButton_3.value = "false";
				(function(radioButton_3){
					radioButton_3.setItemSet(app.lookup("radio"), {
						"label": "label",
						"value": "value"
					})
				})(radioButton_3);
				container.addChild(radioButton_3, {
					"colIndex": 1,
					"rowIndex": 6
				});
				var inputBox_1 = new cpr.controls.InputBox("col2_2");
				container.addChild(inputBox_1, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var inputBox_2 = new cpr.controls.InputBox("col2_4");
				container.addChild(inputBox_2, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var inputBox_3 = new cpr.controls.InputBox("col2_5");
				inputBox_3.value = "'['+value+']'+label";
				container.addChild(inputBox_3, {
					"colIndex": 1,
					"rowIndex": 4
				});
				var inputBox_4 = new cpr.controls.InputBox("col2_6");
				container.addChild(inputBox_4, {
					"colIndex": 1,
					"rowIndex": 5
				});
				var inputBox_5 = new cpr.controls.InputBox("col2_8");
				container.addChild(inputBox_5, {
					"colIndex": 1,
					"rowIndex": 7
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = "menuType";
				container.addChild(output_9, {
					"colIndex": 0,
					"rowIndex": 8
				});
				var radioButton_4 = new cpr.controls.RadioButton("col2_9");
				radioButton_4.value = "megamenu";
				(function(radioButton_4){
					radioButton_4.addItem(new cpr.controls.Item("menu", "menu"));
					radioButton_4.addItem(new cpr.controls.Item("megamenu", "megamenu"));
				})(radioButton_4);
				container.addChild(radioButton_4, {
					"colIndex": 1,
					"rowIndex": 8
				});
				var button_9 = new cpr.controls.Button();
				button_9.value = "Apply";
				button_9.userAttr({
					"index": "9",
					"property": "menuType"
				});
				if(typeof onBtn1Click == "function") {
					button_9.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_9, {
					"colIndex": 2,
					"rowIndex": 8
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "313px",
				"left": "10px",
				"width": "495px",
				"height": "319px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txa1");
			textArea_1.value = "var nav = app.lookup(\"nav1\");\r\nconsole.log(nav.value);";
			container.addChild(textArea_1, {
				"top": "313px",
				"right": "10px",
				"left": "525px",
				"height": "319px"
			});
			
			var button_10 = new cpr.controls.Button();
			button_10.value = "execute";
			if(typeof onButtonClick == "function") {
				button_10.addEventListener("click", onButtonClick);
			}
			container.addChild(button_10, {
				"top": "283px",
				"left": "635px",
				"width": "100px",
				"height": "20px"
			});
			
			var output_10 = new cpr.controls.Output();
			output_10.value = "스크립트";
			container.addChild(output_10, {
				"top": "283px",
				"left": "525px",
				"width": "100px",
				"height": "20px"
			});
			
			var output_11 = new cpr.controls.Output();
			output_11.value = "속성";
			container.addChild(output_11, {
				"top": "283px",
				"left": "10px",
				"width": "100px",
				"height": "20px"
			});
			
			var userDefinedControl_1 = new udc.pagetitle2();
			userDefinedControl_1.bind("title").toAppProperty("title");
			userDefinedControl_1.bind("explain").toAppProperty("explain");
			container.addChild(userDefinedControl_1, {
				"top": "20px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
		}
	});
	app.title = "nav_megamenu";
	cpr.core.Platform.INSTANCE.register(app);
})();
