/*
 * App URI: example/component/nav_mobile
 * Source Location: example/component/nav_mobile.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/component/nav_mobile", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			
			/*
			 * 사용자 정의 컨트롤에서 selection-change 이벤트 발생 시 호출.
			 */
			function onNavigationBarSelectionChange(/* cpr.events.CUIEvent */ e){
				/** 
				 * @type udc.NavigationBar
				 */
				var navigationBar = e.control;
				
				app.lookup("opt1").value = e.content.item.label; 
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.NavigationBar();
			if(typeof onNavigationBarSelectionChange == "function") {
				userDefinedControl_1.addEventListener("selection-change", onNavigationBarSelectionChange);
			}
			container.addChild(userDefinedControl_1, {
				"top": "80px",
				"right": "0px",
				"left": "20px",
				"height": "50px"
			});
			
			var userDefinedControl_2 = new udc.pagetitle2();
			userDefinedControl_2.bind("title").toAppProperty("title");
			userDefinedControl_2.bind("explain").toAppProperty("explain");
			container.addChild(userDefinedControl_2, {
				"top": "20px",
				"right": "0px",
				"left": "20px",
				"height": "50px"
			});
			
			var output_1 = new cpr.controls.Output("opt1");
			output_1.value = "Output";
			container.addChild(output_1, {
				"top": "204px",
				"left": "111px",
				"width": "253px",
				"height": "20px"
			});
			
			var output_2 = new cpr.controls.Output();
			output_2.value = "선택된 메뉴:";
			container.addChild(output_2, {
				"top": "204px",
				"left": "20px",
				"width": "81px",
				"height": "20px"
			});
		}
	});
	app.title = "nav_mobile";
	cpr.core.Platform.INSTANCE.register(app);
})();
