/*
 * App URI: example/component/selectItem_depth
 * Source Location: example/component/selectItem_depth.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/component/selectItem_depth", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * listbox_ex.js
			 * Created at 2018. 8. 13. 오후 4:59:31.
			 * 
			 * @author leeds
			 ************************************************/
			
			
			
			/*
			 * "select" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				app.lookup("llb1").selectItemByValue("Item 1.2.2");
			}
			
			
			/*
			 * "select" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn2 = e.control;
				app.lookup("lcb1").selectItemByValue("Item 1.2.2");
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			app.declareBindableAppProperty("explain", null);
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"},
					{"name": "parentValue"}
				],
				"rows": [
					{"label": "Item 1", "value": "Item 1", "parentValue": ""},
					{"label": "Item 2", "value": "Item 2", "parentValue": ""},
					{"label": "Item 3", "value": "Item 3", "parentValue": ""},
					{"label": "Item 1.1", "value": "Item 1.1", "parentValue": "Item 1"},
					{"label": "Item 1.2", "value": "Item 1.2", "parentValue": "Item 1"},
					{"label": "Item 1.2.1", "value": "Item 1.2.1", "parentValue": "Item 1.2"},
					{"label": "Item 1.2.2", "value": "Item 1.2.2", "parentValue": "Item 1.2"},
					{"label": "Item 1.2.3", "value": "Item 1.2.3", "parentValue": "Item 1.2"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var linkedListBox_1 = new cpr.controls.LinkedListBox("llb1");
			(function(linkedListBox_1){
				linkedListBox_1.setItemSet(app.lookup("ds1"), {
					"label": "label",
					"value": "value",
					"parentValue": "parentValue"
				});
			})(linkedListBox_1);
			container.addChild(linkedListBox_1, {
				"top": "150px",
				"left": "40px",
				"width": "400px",
				"height": "150px"
			});
			
			var linkedComboBox_1 = new cpr.controls.LinkedComboBox("lcb1");
			(function(linkedComboBox_1){
				linkedComboBox_1.setItemSet(app.lookup("ds1"), {
					"label": "label",
					"value": "value",
					"parentValue": "parentValue"
				});
			})(linkedComboBox_1);
			linkedComboBox_1.placeholders = [
			];
			container.addChild(linkedComboBox_1, {
				"top": "410px",
				"left": "40px",
				"width": "400px",
				"height": "30px"
			});
			
			var userDefinedControl_1 = new udc.pagetitle2();
			userDefinedControl_1.bind("explain").toAppProperty("explain");
			userDefinedControl_1.bind("title").toAppProperty("title");
			container.addChild(userDefinedControl_1, {
				"top": "10px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
			
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "select";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "100px",
				"left": "40px",
				"width": "100px",
				"height": "30px"
			});
			
			var button_2 = new cpr.controls.Button("btn2");
			button_2.value = "select";
			if(typeof onBtn2Click == "function") {
				button_2.addEventListener("click", onBtn2Click);
			}
			container.addChild(button_2, {
				"top": "360px",
				"left": "40px",
				"width": "100px",
				"height": "30px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "select item 1.2.2";
			container.addChild(output_1, {
				"top": "100px",
				"left": "160px",
				"width": "280px",
				"height": "30px"
			});
			
			var output_2 = new cpr.controls.Output();
			output_2.value = "select item 1.2.2";
			container.addChild(output_2, {
				"top": "360px",
				"left": "160px",
				"width": "280px",
				"height": "30px"
			});
		}
	});
	app.title = "selectItem_depth";
	cpr.core.Platform.INSTANCE.register(app);
})();
