/*
 * App URI: 1-Layout/Advanced/DynamicContent2
 * Source Location: 1-Layout/Advanced/DynamicContent2.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("1-Layout/Advanced/DynamicContent2", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			var itemCount = 0;
			var cardWidth = 120;
			var cardHeight = 160;
			/*
			 * Body에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit( /* cpr.events.CEvent */ e) {
				var layout = new cpr.controls.layouts.FormLayout();
				layout.setRows(["25px"]);
				layout.setColumns(["1fr", cardWidth + "px", cardWidth + "px", cardWidth + "px", cardWidth + "px", "1fr"]);
			
				var pane = app.lookup("contentPane");
				pane.setLayout(layout);
			
				var header = app.lookup("header");
				pane.updateConstraint(header, {
					colIndex: 0,
					rowIndex: 0,
					colSpan: 6
				});
			
				app.getContainer().updateConstraint(pane, {
					"position": "fixed"
				});
			
				var top = app.lookup("top");
				app.getContainer().updateConstraint(top, {
					position: "fixed"
				});
			
				var left = app.lookup("left");
				app.getContainer().updateConstraint(left, {
					position: "fixed"
				});
			}
			
			/*
			 * "콘텐트 추가" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				itemCount++;
			
				var newBtn = new udc.PersonCard();
				newBtn.title = "사람" + itemCount;
			
				var rowIdx = Math.floor((itemCount - 1) / 4) + 1;
				var colIdx = (itemCount - 1) % 4;
			
				var rowCount = Math.floor(itemCount / 4) + 1;
				if (itemCount % 4 !== 0) {
					rowCount++;
				}
			
				var pane = app.lookup("contentPane");
			
				/** @type cpr.controls.layouts.FormLayout */
				var layout = pane.getLayout();
				var rows = [];
				for (var idx = 0; idx < rowCount; idx++) {
					if (idx === 0) {
						rows.push("25px");
					} else {
						rows.push(cardHeight + "px");
					}
				}
				layout.setRows(rows);
			
				app.lookup("contentPane").addChild(newBtn, {
					colIndex: colIdx + 1,
					rowIndex: rowIdx
				});
			
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("contentPane");
			group_1.style.css({
				"background-color" : "orange",
				"background-image" : "none"
			});
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("header");
				// Layout
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var button_1 = new cpr.controls.Button();
					button_1.value = "+ 콘텐트 추가";
					if(typeof onButtonClick == "function") {
						button_1.addEventListener("click", onButtonClick);
					}
					container.addChild(button_1, {
						"right": "20px",
						"width": "100px",
						"height": "20px",
						"top": "calc(50% - 10px)"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "20px",
					"left": "20px",
					"width": "679px",
					"height": "51px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "39px",
				"right": "0px",
				"bottom": "40px",
				"left": "146px"
			});
			
			var navigationBar_1 = new cpr.controls.NavigationBar("top");
			(function(navigationBar_1){
				navigationBar_1.addItem(new cpr.controls.MenuItem("label1", "value1", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label2", "value2", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label3", "value3", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label4", "value4", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label5", "value5", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label6", "value6", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label7", "value7", null));
				navigationBar_1.addItem(new cpr.controls.MenuItem("label8", "value8", null));
			})(navigationBar_1);
			container.addChild(navigationBar_1, {
				"top": "0px",
				"right": "0px",
				"left": "0px",
				"height": "40px"
			});
			
			var listBox_1 = new cpr.controls.ListBox("left");
			(function(listBox_1){
				listBox_1.addItem(new cpr.controls.Item("label1", "value1"));
				listBox_1.addItem(new cpr.controls.Item("label2", "value2"));
				listBox_1.addItem(new cpr.controls.Item("label3", "value3"));
				listBox_1.addItem(new cpr.controls.Item("label4", "value4"));
				listBox_1.addItem(new cpr.controls.Item("label5", "value5"));
				listBox_1.addItem(new cpr.controls.Item("label6", "value6"));
				listBox_1.addItem(new cpr.controls.Item("label7", "value7"));
			})(listBox_1);
			container.addChild(listBox_1, {
				"top": "39px",
				"bottom": "0px",
				"left": "0px",
				"width": "147px"
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "Footer";
			container.addChild(button_2, {
				"right": "0px",
				"bottom": "0px",
				"left": "146px",
				"height": "41px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "DynamicContent2";
	cpr.core.Platform.INSTANCE.register(app);
})();
