/*
 * App URI: 6-UDC/Advanced/Message
 * Source Location: 6-UDC/Advanced/Message.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("6-UDC/Advanced/Message", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("test");
			dataSet_1.parseData({
				"columns": [
					{"name": "reuseId"},
					{"name": "value"},
					{
						"name": "height",
						"dataType": "number"
					}
				],
				"rows": [
					{"reuseId": "6-UDC/Advanced/Section", "value": "Group1", "height": "30"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data1", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data2", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data3", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data4", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Section", "value": "Group2", "height": "30"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data1", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data2", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Section", "value": "Group3", "height": "30"},
					{"reuseId": "6-UDC/Advanced/Message", "value": "data1", "height": "50"},
					{"reuseId": "6-UDC/Advanced/Section", "value": "Group4", "height": "30"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.setColumns(["1fr", "100px"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.bind("value").toDataColumn("value");
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "Open";
				container.addChild(button_1, {
					"colIndex": 1,
					"rowIndex": 0,
					"verticalAlign": "center"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0px",
				"right": "10px",
				"bottom": "0px",
				"left": "20px"
			});
		}
	});
	app.title = "Message";
	cpr.core.Platform.INSTANCE.register(app);
})();
