/*
 * App URI: example/plugin/chart
 * Source Location: example/plugin/chart.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/plugin/chart", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			/*
			 * 쉘에서 init 이벤트 발생 시 호출.
			 */
			function onUIControlShellInit(/* cpr.events.CUIEvent */ e){
				/** 
				 * @type cpr.controls.UIControlShell
				 */
				var uIControlShell = e.control;
				
				// chart가 새로 그려지기 전에 기존에 echart 관련 객체가 있으면 삭제한다.
				var shellDiv = e.content;
				if(shellDiv){
					var instance = echarts.getInstanceByDom(shellDiv);
					if(instance){
						instance.dispose();
					}
				}
			}
			
			/*
			 * 쉘에서 load 이벤트 발생 시 호출.
			 */
			function onUIControlShellLoad(/* cpr.events.CUIEvent */ e){
				/** 
				 * @type cpr.controls.UIControlShell
				 */
				var uIControlShell = e.control;
				
				// div에 echart를 입히는 코드
				var shellDiv = e.content;
				if(!shellDiv){
					return;
				}
				var myChart = echarts.init(shellDiv);
				var option = {
					title : {
						text : 'ECharts 연동 예제'
					},
					tooltip : {},
					legend : {
						data : [ 'Sales' , 'Marketing', "R&D"]
					},
					xAxis : {
						data : [ "shirt", "cardign", "chiffon shirt", "pants", "heels", "socks" ]
					},
					yAxis : {},
					series : [ {
						name : 'Sales',
						type : 'bar',
						data : [ 5, 20, 36, 10, 10, 20 ]
					},
					{
						name : 'Marketing',
						type : 'line',
						data : [ 15, 25, 20, 25, 24, 40 ]
					},
					{
						name : 'R&D',
						type : 'bar',
						data : [ 15, 20, 35, 33, 40, 35 ]
					}]
				};
				myChart.setOption(option);
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var uIControlShell_1 = new cpr.controls.UIControlShell();
			if(typeof onUIControlShellInit == "function") {
				uIControlShell_1.addEventListener("init", onUIControlShellInit);
			}
			if(typeof onUIControlShellLoad == "function") {
				uIControlShell_1.addEventListener("load", onUIControlShellLoad);
			}
			container.addChild(uIControlShell_1, {
				"top": "10px",
				"right": "58px",
				"bottom": "10px",
				"left": "10px"
			});
		}
	});
	app.title = "chart";
	cpr.core.Platform.INSTANCE.register(app);
})();
