/*
 * App URI: example/submission/tsvprotocal
 * Source Location: example/submission/tsvprotocal.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("example/submission/tsvprotocal", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			/*
			 * "조회" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				
				// 조회 submission, 데이터를 전송합니다. 이미 동일한 서브미션으로 전송 중인 경우 실행되지 않습니다.
				app.lookup("subMain").send();
			}
			
			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSubMainSubmitSuccess(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var subMain = e.control;
				
				// 그리드 컨트롤을 다시 그립니다.
				app.lookup("grd1").redraw();
			}
			
			
			
			/*
			 * "초기화" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				
				// 모든 데이터셋 정보를 제거합니다.
				app.lookup("mainDS").clear();
				
				// 그리드 컨트롤을 다시 그립니다.
				app.lookup("grd1").redraw();
			}
			
			/*
			 * 서브미션에서 submit-progress 이벤트 발생 시 호출.
			 * 서버로 부터 일정 크기의 데이터를 전송받았을 때 발생합니다. 하나의 응답에 대해 여러 번 발생할 수 있습니다.
			 */
			function onSubMainSubmitProgress(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var subMain = e.control;
				
				// 그리드 컨트롤을 다시 그립니다.
				app.lookup("grd1").redraw();
			};
			// End - User Script
			
			// Header
			app.declareBindableAppProperty("title", null);
			app.declareBindableAppProperty("explain", null);
			var dataSet_1 = new cpr.data.DataSet("mainDS");
			dataSet_1.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{
						"name": "column6",
						"dataType": "number"
					},
					{
						"name": "column7",
						"dataType": "number"
					},
					{
						"name": "column8",
						"dataType": "number"
					},
					{
						"name": "column9",
						"dataType": "number"
					},
					{
						"name": "column10",
						"dataType": "number"
					}
				]
			});
			app.register(dataSet_1);
			var submission_1 = new cpr.protocols.Submission("subMain");
			submission_1.async = true;
			submission_1.action = "../example/tsvprotocal/massdata.do";
			submission_1.addResponseData(dataSet_1, false);
			if(typeof onSubMainSubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSubMainSubmitSuccess);
			}
			if(typeof onSubMainSubmitProgress == "function") {
				submission_1.addEventListener("submit-progress", onSubMainSubmitProgress);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("subExport");
			submission_2.action = "../export/그리드.xlsx";
			submission_2.responseType = "blob";
			app.register(submission_2);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "조회";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "70px",
				"right": "90px",
				"width": "70px",
				"height": "20px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("mainDS"),
				"columnMovable": true,
				"columnResizable": true,
				"selectionMulti": "multi",
				"leftSplit": 0,
				"leftSplitWidth": 0,
				"columns": [
					{"width": "43px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "110px"},
					{"width": "110px"},
					{"width": "110px"},
					{"width": "110px"},
					{"width": "110px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 2},
							"configurator": function(cell){
								cell.text = "헤더1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.text = "헤더2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.text = "헤더3";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.text = "헤더4";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.text = "헤더5";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.text = "헤더6";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.text = "헤더7";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.text = "헤더8";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 9},
							"configurator": function(cell){
								cell.text = "헤더9";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 10},
							"configurator": function(cell){
								cell.text = "헤더10";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnType = "rowindex";
								cell.style.css({
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "column4";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.columnName = "column5";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.columnName = "column6";
								cell.control = (function(){
									var output_1 = new cpr.controls.Output();
									output_1.dataType = "number";
									output_1.format = "000,000,000,000";
									output_1.style.css({
										"text-align" : "right"
									});
									output_1.bind("value").toDataColumn("column6");
									return output_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.columnName = "column7";
								cell.columnType = "normal";
								cell.suppressible = false;
								cell.suppressRef = -1;
								cell.control = (function(){
									var output_2 = new cpr.controls.Output();
									output_2.dataType = "number";
									output_2.format = "000,000,000,000";
									output_2.style.css({
										"text-align" : "right"
									});
									output_2.bind("value").toDataColumn("column7");
									return output_2;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.columnName = "column8";
								cell.columnType = "normal";
								cell.suppressible = false;
								cell.suppressRef = -1;
								cell.control = (function(){
									var output_3 = new cpr.controls.Output();
									output_3.dataType = "number";
									output_3.format = "000,000,000,000";
									output_3.style.css({
										"text-align" : "right"
									});
									output_3.bind("value").toDataColumn("column8");
									return output_3;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 9},
							"configurator": function(cell){
								cell.columnName = "column9";
								cell.columnType = "normal";
								cell.suppressible = false;
								cell.suppressRef = -1;
								cell.control = (function(){
									var output_4 = new cpr.controls.Output();
									output_4.dataType = "number";
									output_4.format = "000,000,000,000";
									output_4.style.css({
										"text-align" : "right"
									});
									output_4.bind("value").toDataColumn("column9");
									return output_4;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 10},
							"configurator": function(cell){
								cell.columnName = "column10";
								cell.columnType = "normal";
								cell.suppressible = false;
								cell.suppressRef = -1;
								cell.control = (function(){
									var output_5 = new cpr.controls.Output();
									output_5.dataType = "number";
									output_5.format = "000,000,000,000";
									output_5.style.css({
										"text-align" : "right"
									});
									output_5.bind("value").toDataColumn("column10");
									return output_5;
								})();
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "100px",
				"right": "10px",
				"bottom": "10px",
				"left": "10px"
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "초기화";
			if(typeof onButtonClick2 == "function") {
				button_2.addEventListener("click", onButtonClick2);
			}
			container.addChild(button_2, {
				"top": "70px",
				"right": "10px",
				"width": "70px",
				"height": "20px"
			});
			
			var userDefinedControl_1 = new udc.pagetitle2();
			userDefinedControl_1.bind("title").toAppProperty("title");
			userDefinedControl_1.bind("explain").toAppProperty("explain");
			container.addChild(userDefinedControl_1, {
				"top": "10px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
		}
	});
	app.title = "그리트(대용량)";
	cpr.core.Platform.INSTANCE.register(app);
})();
