/*
 * App URI: TEST/view/testNew
 * Source Location: TEST/view/testNew.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("TEST/view/testNew", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * empNew.js
			 * Created at 2020. 10. 30. 오후 3:53:43.
			 *
			 * @author A
			 ************************************************/
			
			
			
			/*
			 * "취소" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				close();
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 800px) and (max-width: 1023px)", "new-screen");
			app.supportMedia("all and (min-width: 500px) and (max-width: 799px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var button_1 = new cpr.controls.Button();
				button_1.value = "저장";
				container.addChild(button_1, {
					"top": "142px",
					"left": "417px",
					"width": "76px",
					"height": "38px"
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "취소";
				if(typeof onButtonClick == "function") {
					button_2.addEventListener("click", onButtonClick);
				}
				container.addChild(button_2, {
					"top": "142px",
					"left": "504px",
					"width": "75px",
					"height": "38px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "사번";
				output_1.style.css({
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "70px",
					"left": "119px",
					"width": "50px",
					"height": "40px"
				});
				var inputBox_1 = new cpr.controls.InputBox("ipb1");
				container.addChild(inputBox_1, {
					"top": "80px",
					"left": "170px",
					"width": "100px",
					"height": "20px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "직급";
				output_2.style.css({
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"top": "70px",
					"left": "443px",
					"width": "50px",
					"height": "40px"
				});
				var inputBox_2 = new cpr.controls.InputBox("ipb2");
				container.addChild(inputBox_2, {
					"top": "80px",
					"left": "492px",
					"width": "100px",
					"height": "20px"
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "이름";
				output_3.style.css({
					"text-align" : "center"
				});
				container.addChild(output_3, {
					"top": "70px",
					"left": "280px",
					"width": "50px",
					"height": "40px"
				});
				var inputBox_3 = new cpr.controls.InputBox("ipb3");
				container.addChild(inputBox_3, {
					"top": "80px",
					"left": "330px",
					"width": "100px",
					"height": "20px"
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "전화번호";
				output_4.style.css({
					"text-align" : "center"
				});
				container.addChild(output_4, {
					"top": "70px",
					"left": "601px",
					"width": "50px",
					"height": "40px"
				});
				var inputBox_4 = new cpr.controls.InputBox("ipb4");
				container.addChild(inputBox_4, {
					"top": "80px",
					"left": "661px",
					"width": "100px",
					"height": "20px"
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "나이";
				output_5.style.css({
					"text-align" : "center"
				});
				container.addChild(output_5, {
					"top": "70px",
					"left": "771px",
					"width": "50px",
					"height": "40px"
				});
				var inputBox_5 = new cpr.controls.InputBox("ipb6");
				container.addChild(inputBox_5, {
					"top": "80px",
					"left": "820px",
					"width": "100px",
					"height": "20px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0px",
				"left": "0px",
				"width": "1025px",
				"height": "200px"
			});
		}
	});
	app.title = "testNew";
	cpr.core.Platform.INSTANCE.register(app);
})();
